import type { TFn } from "@/i18n/types";

/** QnA / community gallery copy — use with `useI18n().t`. */
export function communityUi(t: TFn) {
  return {
    qna: t("m.common.qna"),
    back: t("m.common.back"),
    newQna: t("m.community.new_qna"),
    category: t("m.common.category"),
    categoryRequiredHint: t("m.community.required_pick_one"),
    attach: t("m.community.attach"),
    attachAddA11y: t("m.community.add_attachment"),
    attachRemoveA11y: t("m.community.remove_attached_photo"),
    createQna: t("m.community.create_qna"),
    createFailTitle: t("m.community.could_not_create"),
    createFailDefault: t("m.community.could_not_create_qna"),
    permTitle: t("m.common.permission_required"),
    photoPerm: t("m.common.photo_library_access_is_required"),
    mediaPerm: t("m.community.photo_and_video_library_access_is"),
    pickCategoryTitle: t("m.common.category"),
    pickCategoryMsg: t("m.community.choose_a_category_for_this_qna"),
    questionTitle: t("m.community.q"),
    questionMinMsg: t("m.community.enter_at_least_2_characters_for"),
    loadQnaError: t("m.community.could_not_load_qna"),
    joinPending: t("m.community.join_request_submitted"),
    joined: t("m.community.you_joined"),
    joinFail: t("m.common.could_not_join"),
    uploadFailTitle: t("m.common.upload_failed"),
    brandingSavedTitle: t("m.common.saved"),
    iconUpdated: t("m.community.icon_updated"),
    bannerUpdated: t("m.community.banner_updated"),
    imageChangeFail: t("m.community.could_not_update_image"),
    tapSetBanner: t("m.community.tap_to_set_banner"),
    uploading: t("m.common.uploading"),
    banner: t("m.community.banner"),
    members: (n: number, locale: string) =>
      t("m.community.n_members", { n: String(n.toLocaleString("en-US")) }),
    brandingTitle: t("m.community.icon_banner"),
    brandingHint: t("m.community.only_members_with_permission_can_change"),
    icon: t("m.community.icon"),
    joinPasswordPh: t("m.community.4_digit_join_password"),
    joinRequest: t("m.community.request_to_join"),
    join: t("m.common.join"),
    enterGallery: t("m.community.enter_gallery"),
    joinedLabel: t("m.common.joined"),
    recentPosts: t("m.community.recent_posts"),
    noPostsYet: t("m.common.no_posts_yet"),
    tabAllPosts: t("m.community.all_posts"),
    tabNotice: t("m.common.notice"),
    noTitle: t("m.community.untitled"),
    noticeNo: t("m.common.notice"),
    views: (n: number) => t("m.community.n_views", { n: String(n) }),
    postTitle: t("m.common.post"),
    postNeedContent: t("m.community.add_text_a_photo_or_a"),
    publishFailTitle: t("m.community.could_not_post"),
    publishFail: t("m.community.could_not_publish_post"),
    fileUploadFail: t("m.community.could_not_upload_file"),
    joinRequestBtn: t("m.community.request_to_join"),
    inviteOnly: t("m.community.invite_only"),
    joinGallery: t("m.community.join_gallery"),
    loadGalleryError: t("m.community.could_not_load_gallery"),
    galleryInfoA11y: t("m.community.gallery_info"),
    browsingGallery: t("m.community.browsing_gallery"),
    browseApproveHint: t("m.community.you_can_read_posts_request_to"),
    browseInviteHint: t("m.community.only_members_with_an_invite_link"),
    browseOpenHint: t("m.community.you_can_read_posts_join_to"),
    joinPasswordSuffix: t("m.community.a_4_digit_password_is_required"),
    passwordPh: t("m.community.4_digit_password"),
    processing: t("m.common.processing"),
    colNo: t("m.community.no"),
    colTitle: t("m.common.title"),
    emptyConcept: t("m.community.no_concept_posts_yet"),
    emptyNotice: t("m.community.no_notices"),
    emptyPosts: t("m.common.no_posts_yet"),
    composerPh: t("m.community.write_a_post"),
    addPhotoA11y: t("m.common.add_photo"),
    addVideoA11y: t("m.community.add_video"),
    posting: t("m.community.posting"),
    submitPost: t("m.common.post"),
  };
}

export type CommunityUi = ReturnType<typeof communityUi>;
