/** QnA / community gallery copy — use with `useI18n().u`. */
export function communityUi(u: (ko: string, en: string) => string) {
  return {
    qna: u("QnA", "QnA"),
    back: u("뒤로", "Back"),
    newQna: u("새 QnA", "New QnA"),
    category: u("카테고리", "Category"),
    categoryRequiredHint: u("필수 · 하나 선택", "Required · pick one"),
    attach: u("첨부", "Attach"),
    attachAddA11y: u("첨부파일 추가", "Add attachment"),
    attachRemoveA11y: u("첨부 사진 삭제", "Remove attached photo"),
    createQna: u("QnA 만들기", "Create QnA"),
    createFailTitle: u("생성 실패", "Could not create"),
    createFailDefault: u("QnA 생성에 실패했습니다.", "Could not create QnA."),
    permTitle: u("권한 필요", "Permission required"),
    photoPerm: u("사진 접근 권한이 필요합니다.", "Photo library access is required."),
    mediaPerm: u("사진과 영상 접근 권한이 필요합니다.", "Photo and video library access is required."),
    pickCategoryTitle: u("카테고리", "Category"),
    pickCategoryMsg: u("QnA가 속할 카테고리를 선택해 주세요.", "Choose a category for this QnA."),
    questionTitle: u("Q", "Q"),
    questionMinMsg: u("질문은 2자 이상 입력해 주세요.", "Enter at least 2 characters for the question."),
    loadQnaError: u("QnA를 불러오지 못했습니다.", "Could not load QnA."),
    joinPending: u("가입 요청이 접수되었습니다.", "Join request submitted."),
    joined: u("가입되었습니다.", "You joined."),
    joinFail: u("가입에 실패했습니다.", "Could not join."),
    uploadFailTitle: u("업로드 실패", "Upload failed"),
    brandingSavedTitle: u("Saved", "Saved"),
    iconUpdated: u("대표 이미지를 변경했습니다.", "Icon updated."),
    bannerUpdated: u("배너를 변경했습니다.", "Banner updated."),
    imageChangeFail: u("이미지 변경에 실패했습니다.", "Could not update image."),
    tapSetBanner: u("탭해서 배너 설정", "Tap to set banner"),
    uploading: u("업로드 중…", "Uploading…"),
    banner: u("배너", "Banner"),
    members: (n: number, locale: string) =>
      u(`${n.toLocaleString(locale === "ko" ? "ko-KR" : "en-US")}명`, `${n.toLocaleString("en-US")} members`),
    brandingTitle: u("대표 이미지 / 배너", "Icon / banner"),
    brandingHint: u(
      "권한이 있는 멤버만 변경할 수 있습니다. 이미지를 탭하거나 아래 버튼을 사용하세요.",
      "Only members with permission can change these. Tap an image or use the buttons below."
    ),
    icon: u("대표 이미지", "Icon"),
    joinPasswordPh: u("가입 비밀번호 4자리", "4-digit join password"),
    joinRequest: u("가입 요청", "Request to join"),
    join: u("가입하기", "Join"),
    enterGallery: u("갤러리 들어가기", "Enter gallery"),
    joinedLabel: u("가입됨", "Joined"),
    recentPosts: u("최근 글", "Recent posts"),
    noPostsYet: u("아직 글이 없습니다.", "No posts yet."),
    tabAllPosts: u("전체글", "All posts"),
    tabNotice: u("공지", "Notice"),
    noTitle: u("(제목 없음)", "(Untitled)"),
    noticeNo: u("공지", "Notice"),
    views: (n: number) => u(`조회 ${n}`, `${n} views`),
    postTitle: u("글", "Post"),
    postNeedContent: u("내용이나 사진, 영상을 넣어 주세요.", "Add text, a photo, or a video."),
    publishFailTitle: u("게시 실패", "Could not post"),
    publishFail: u("글을 올리지 못했습니다.", "Could not publish post."),
    fileUploadFail: u("파일을 올리지 못했습니다.", "Could not upload file."),
    joinRequestBtn: u("가입 요청하기", "Request to join"),
    inviteOnly: u("초대 필요", "Invite only"),
    joinGallery: u("갤러리 참여하기", "Join gallery"),
    loadGalleryError: u("갤러리를 불러오지 못했습니다.", "Could not load gallery."),
    galleryInfoA11y: u("갤러리 정보", "Gallery info"),
    browsingGallery: u("갤러리 둘러보기 중", "Browsing gallery"),
    browseApproveHint: u(
      "글은 읽을 수 있습니다. 쓰려면 가입 요청을 보내세요.",
      "You can read posts. Request to join to write."
    ),
    browseInviteHint: u(
      "초대 링크가 있는 멤버만 참여할 수 있습니다.",
      "Only members with an invite link can participate."
    ),
    browseOpenHint: u(
      "글은 읽을 수 있습니다. 참여하면 글·댓글을 작성할 수 있어요.",
      "You can read posts. Join to write posts and comments."
    ),
    joinPasswordSuffix: u(" 가입 시 4자리 비밀번호가 필요합니다.", " A 4-digit password is required to join."),
    passwordPh: u("비밀번호 4자리", "4-digit password"),
    processing: u("처리 중…", "Processing…"),
    colNo: u("번호", "No."),
    colTitle: u("제목", "Title"),
    emptyConcept: u("개념글이 없습니다.", "No concept posts yet."),
    emptyNotice: u("공지가 없습니다.", "No notices."),
    emptyPosts: u("등록된 글이 없습니다.", "No posts yet."),
    composerPh: u("글 남기기", "Write a post"),
    addPhotoA11y: u("사진 추가", "Add photo"),
    addVideoA11y: u("영상 추가", "Add video"),
    posting: u("올리는 중", "Posting"),
    submitPost: u("등록", "Post"),
  };
}

export type CommunityUi = ReturnType<typeof communityUi>;
