/** Static public routes indexed for search engines (no auth-required areas). */
export const PUBLIC_SITEMAP_PATHS = [
  "/",
  "/explore",
  "/reels",
  "/live",
  "/market",
  "/anime",
  "/anime/popular",
  "/anime/recent",
  "/anime/random",
  "/communities",
  "/search",
  "/rankings",
  "/discover",
  "/games",
  "/cosplay",
  "/cosplay/profiles",
  "/works",
  "/flowers",
  "/money",
  "/legal",
  "/legal/aup",
  "/legal/policy",
  "/legal/culture-wiki",
  "/legal/terms",
  "/legal/creator-terms",
  "/legal/seller-terms",
  "/legal/sponsored-content",
  "/legal/payment",
  "/legal/copyright",
  "/legal/privacy",
  "/legal/account-deletion",
  "/legal/moderation",
  "/auth/signin",
  "/auth/signup",
] as const;
