import type { SubcultureMapMustSearchEntry } from "@/lib/subculture-map-must-search";

/** 대만·미국 상설 메이드 카페 — must-search (확정 좌표 + sync 시 재검색) */
export const SUBCULTURE_MAP_MUST_SEARCH_INTL: SubcultureMapMustSearchEntry[] = [
  // ── Taipei / Ximending ──
  {
    name: "月讀女僕咖啡 台北西門店",
    category: "maid_cafe",
    country: "tw",
    city: "台北市萬華區",
    address: "108台灣台北市萬華區成都路10號4樓",
    lat: 25.042093,
    lng: 121.506389,
    sourceUrl: "https://ko.akihabara-bc.jp/akiba-tukuyomi/",
    id: "tsukuyomi-ximen",
  },
  {
    name: "萌姬女僕咖啡館",
    category: "maid_cafe",
    country: "tw",
    city: "台北市萬華區",
    address: "108台灣台北市萬華區漢中街43號6樓",
    lat: 25.04418,
    lng: 121.50702,
    sourceUrl: "https://taiwanderers.com/themed-cafes-restaurants-taiwan/",
    id: "moe-hime",
  },
  {
    name: "心物語 Kokorolia Maid Café",
    category: "maid_cafe",
    country: "tw",
    city: "台北市萬華區",
    address: "108台灣台北市萬華區武昌街二段17之62號2樓",
    lat: 25.04365,
    lng: 121.50785,
    id: "kokorolia",
  },
  {
    name: "夢見女僕咖啡館",
    category: "maid_cafe",
    country: "tw",
    city: "台北市大安區",
    address: "106台灣台北市大安區復興南路二段148巷17號",
    lat: 25.02642,
    lng: 121.54388,
    sourceUrl: "https://www.facebook.com/YumemiMaid/",
    id: "yumemi",
  },
  {
    name: "蕾菲亞 Lefiya 女僕咖啡廳",
    category: "maid_cafe",
    country: "tw",
    city: "台北市萬華區",
    address: "108台灣台北市萬華區峨眉街84巷6號2樓",
    lat: 25.04452,
    lng: 121.50672,
    id: "lefiya",
  },
  {
    name: "喫茶 朱雫 Maid Café",
    category: "maid_cafe",
    country: "tw",
    city: "台北市中正區",
    address: "100台灣台北市中正區信義路二段198巷35號",
    lat: 25.03312,
    lng: 121.52488,
    id: "akashizuku",
  },
  {
    name: "魔女學院女僕咖啡廳",
    category: "maid_cafe",
    country: "tw",
    city: "台北市萬華區",
    address: "108台灣台北市萬華區成都路10號3樓",
    note: "Next to Tsukuyomi Ximen",
    lat: 25.042093,
    lng: 121.506389,
    id: "witch-hat",
  },
  {
    name: "阿克蒂雅 Arkadia 女僕咖啡",
    category: "maid_cafe",
    country: "tw",
    city: "台北市中正區",
    address: "100台灣台北市中正區八德路一段82巷8弄4號",
    lat: 25.04782,
    lng: 121.53245,
    id: "arkadia",
  },
  {
    name: "KIRABASE 台北車站店",
    category: "maid_cafe",
    country: "tw",
    city: "台北市中正區",
    address: "100台灣台北市中正區忠孝西路一段36號6樓",
    lat: 25.04672,
    lng: 121.51588,
    id: "kirabase-tpe",
  },
  // ── Taichung ──
  {
    name: "月讀女僕咖啡 台中車站店",
    category: "maid_cafe",
    country: "tw",
    city: "台中市中區",
    address: "401台灣台中市中區中山路295號",
    lat: 24.13742,
    lng: 120.68512,
    id: "tsukuyomi-taichung",
  },
  {
    name: "曙光 Aurore Maid Café",
    category: "maid_cafe",
    country: "tw",
    city: "台中市西區",
    address: "403台灣台中市西區五權路1之67號22樓",
    lat: 24.14482,
    lng: 120.66342,
    id: "aurore-taichung",
  },
  // ── Kaohsiung ──
  {
    name: "月讀女僕咖啡 五福店",
    category: "maid_cafe",
    country: "tw",
    city: "高雄市新興區",
    address: "800台灣高雄市新興區五福二路57號22樓",
    lat: 22.63182,
    lng: 120.30142,
    id: "tsukuyomi-kaohsiung",
  },
  // ── United States ──
  {
    name: "Asayoru Maid Cafe",
    category: "maid_cafe",
    country: "us",
    city: "Monterey Park, CA",
    address: "500 N Atlantic Blvd Suite 125, Monterey Park, CA 91754, USA",
    lat: 34.062886,
    lng: -118.131313,
    sourceUrl: "https://www.asayorumaidcafe.com/",
    id: "asayoru",
  },
  {
    name: "Arcane Maid Café",
    category: "maid_cafe",
    country: "us",
    city: "Arcadia, CA",
    address: "171 E Live Oak Ave Ste D, Arcadia, CA 91006, USA",
    lat: 34.109622,
    lng: -118.029922,
    sourceUrl: "https://arcanecafe.com/",
    id: "arcane-arcadia",
  },
  {
    name: "Dreamland Anime Café (La Habra)",
    category: "maid_cafe",
    country: "us",
    city: "La Habra, CA",
    address: "1281 E La Habra Blvd #6, La Habra, CA 90631, USA",
    lat: 33.930512,
    lng: -117.945218,
    sourceUrl: "https://www.dreamlandmaidcafe.com/",
    id: "dreamland-la-habra",
  },
  {
    name: "Mirai Maid Cafe",
    category: "maid_cafe",
    country: "us",
    city: "Orlando, FL",
    address: "Orlando, Florida, USA",
    note: "Neo Orlando pop-up / event cafe — confirm via miraimaidcafe.com",
    lat: 28.538336,
    lng: -81.379234,
    sourceUrl: "https://miraimaidcafe.com/",
    id: "mirai-orlando",
  },
];
