/** 서브컬처 행사 지원 ISO alpha-2 (소문자) */
export const SUBCULTURE_COUNTRY_CODES = [
  "kr",
  "us",
  "jp",
  "cn",
  "tw",
  "th",
  "vn",
  "ph",
  "id",
  "sg",
  "my",
  "la",
  "kh",
  "mm",
  "bn",
  "hk",
  "mo",
  "gb",
  "fr",
  "de",
  "es",
  "it",
  "ru",
  "ca",
  "br",
  "mx",
  "ar",
  "cl",
  "co",
  "pe",
  "au",
  "nz",
  "fi",
  "se",
  "no",
  "dk",
  "pl",
  "ro",
  "hu",
  "cz",
  "at",
  "ch",
  "nl",
  "be",
  "pt",
  "gr",
  "ua",
  "tr",
  "sa",
  "ae",
  "il",
  "za",
] as const;

export type SubcultureEventCountryCode = (typeof SUBCULTURE_COUNTRY_CODES)[number];

/** 국가별 Wikipedia·Nominatim 검색 설정 (현지어 쿼리) */
export type GlobalDiscoveryRegion = {
  country: SubcultureEventCountryCode;
  iso: string;
  wikipediaLang: string;
  acceptLanguage: string;
  center: { lat: number; lng: number };
  zoom: number;
  /** 현지어 검색어 — 애니·코믹·コスプレ 등 */
  queries: string[];
};

export const GLOBAL_DISCOVERY_REGIONS: GlobalDiscoveryRegion[] = [
  {
    country: "kr",
    iso: "kr",
    wikipediaLang: "ko",
    acceptLanguage: "ko-KR,ko;q=0.9,en;q=0.5",
    center: { lat: 36.5, lng: 127.8 },
    zoom: 7,
    queries: ["애니메이션 행사", "코믹월드", "서브컬처 페스티벌", "메이드 카페"],
  },
  {
    country: "jp",
    iso: "jp",
    wikipediaLang: "ja",
    acceptLanguage: "ja-JP,ja;q=0.9,en;q=0.5",
    center: { lat: 36.2, lng: 138.2 },
    zoom: 5,
    queries: ["アニメイベント", "コミックマーケット", "コスプレイベント", "メイドカフェ"],
  },
  {
    country: "us",
    iso: "us",
    wikipediaLang: "en",
    acceptLanguage: "en-US,en;q=0.9",
    center: { lat: 39.8, lng: -98.5 },
    zoom: 4,
    queries: ["anime convention United States", "comic con", "anime expo"],
  },
  {
    country: "cn",
    iso: "cn",
    wikipediaLang: "zh",
    acceptLanguage: "zh-CN,zh;q=0.9,en;q=0.5",
    center: { lat: 35.0, lng: 105.0 },
    zoom: 4,
    queries: ["动漫展会", "同人展", "中国国际动漫节"],
  },
  {
    country: "tw",
    iso: "tw",
    wikipediaLang: "zh",
    acceptLanguage: "zh-TW,zh;q=0.9,en;q=0.5",
    center: { lat: 23.7, lng: 121.0 },
    zoom: 7,
    queries: ["開拓動漫祭", "台灣動漫展", "Cosplay 活動"],
  },
  {
    country: "th",
    iso: "th",
    wikipediaLang: "th",
    acceptLanguage: "th-TH,th;q=0.9,en;q=0.5",
    center: { lat: 13.7, lng: 100.5 },
    zoom: 6,
    queries: ["งานอนิเมะ", "คอมิคคอน", "Cosplay"],
  },
  {
    country: "vn",
    iso: "vn",
    wikipediaLang: "vi",
    acceptLanguage: "vi-VN,vi;q=0.9,en;q=0.5",
    center: { lat: 16.0, lng: 108.0 },
    zoom: 5,
    queries: ["lễ hội anime", "cosplay Việt Nam", "triển lãm manga"],
  },
  {
    country: "ph",
    iso: "ph",
    wikipediaLang: "en",
    acceptLanguage: "en-PH,en;q=0.9,fil;q=0.8",
    center: { lat: 12.8, lng: 122.0 },
    zoom: 5,
    queries: ["Anime Festival Asia Philippines", "comic con Manila"],
  },
  {
    country: "id",
    iso: "id",
    wikipediaLang: "id",
    acceptLanguage: "id-ID,id;q=0.9,en;q=0.5",
    center: { lat: -2.5, lng: 118.0 },
    zoom: 4,
    queries: ["festival anime Indonesia", "cosplay Jakarta", "komik con"],
  },
  {
    country: "sg",
    iso: "sg",
    wikipediaLang: "en",
    acceptLanguage: "en-SG,en;q=0.9,zh;q=0.8",
    center: { lat: 1.35, lng: 103.8 },
    zoom: 11,
    queries: ["Anime Festival Asia Singapore", "cosplay Singapore"],
  },
  {
    country: "my",
    iso: "my",
    wikipediaLang: "ms",
    acceptLanguage: "ms-MY,ms;q=0.9,en;q=0.8",
    center: { lat: 4.2, lng: 101.7 },
    zoom: 6,
    queries: ["Comic Fiesta", "anime convention Malaysia"],
  },
  {
    country: "hk",
    iso: "hk",
    wikipediaLang: "zh",
    acceptLanguage: "zh-HK,zh;q=0.9,en;q=0.8",
    center: { lat: 22.3, lng: 114.2 },
    zoom: 10,
    queries: ["香港動漫電玩節", "Cosplay 香港"],
  },
  {
    country: "mo",
    iso: "mo",
    wikipediaLang: "zh",
    acceptLanguage: "zh-MO,zh;q=0.9,pt;q=0.7",
    center: { lat: 22.2, lng: 113.5 },
    zoom: 12,
    queries: ["澳門動漫節", "cosplay 澳門"],
  },
  {
    country: "gb",
    iso: "gb",
    wikipediaLang: "en",
    acceptLanguage: "en-GB,en;q=0.9",
    center: { lat: 54.0, lng: -2.5 },
    zoom: 6,
    queries: ["MCM Comic Con", "anime convention UK"],
  },
  {
    country: "fr",
    iso: "fr",
    wikipediaLang: "fr",
    acceptLanguage: "fr-FR,fr;q=0.9,en;q=0.5",
    center: { lat: 46.6, lng: 2.2 },
    zoom: 6,
    queries: ["Japan Expo", "salon manga", "convention anime France"],
  },
  {
    country: "de",
    iso: "de",
    wikipediaLang: "de",
    acceptLanguage: "de-DE,de;q=0.9,en;q=0.5",
    center: { lat: 51.2, lng: 10.4 },
    zoom: 6,
    queries: ["DoKomi", "Anime Messe", "Comic Con Germany"],
  },
  {
    country: "es",
    iso: "es",
    wikipediaLang: "es",
    acceptLanguage: "es-ES,es;q=0.9,en;q=0.5",
    center: { lat: 40.4, lng: -3.7 },
    zoom: 6,
    queries: ["Japan Weekend", "salón del manga", "convención anime España"],
  },
  {
    country: "it",
    iso: "it",
    wikipediaLang: "it",
    acceptLanguage: "it-IT,it;q=0.9,en;q=0.5",
    center: { lat: 42.5, lng: 12.5 },
    zoom: 6,
    queries: ["Lucca Comics & Games", "festival anime Italia"],
  },
  {
    country: "ru",
    iso: "ru",
    wikipediaLang: "ru",
    acceptLanguage: "ru-RU,ru;q=0.9,en;q=0.5",
    center: { lat: 55.8, lng: 37.6 },
    zoom: 4,
    queries: ["фестиваль аниме", "комик-кон", "Игромир"],
  },
  {
    country: "ca",
    iso: "ca",
    wikipediaLang: "en",
    acceptLanguage: "en-CA,en;q=0.9,fr;q=0.8",
    center: { lat: 56.0, lng: -96.0 },
    zoom: 4,
    queries: ["Anime North", "Fan Expo Canada", "comic con Canada"],
  },
  {
    country: "br",
    iso: "br",
    wikipediaLang: "pt",
    acceptLanguage: "pt-BR,pt;q=0.9,en;q=0.5",
    center: { lat: -14.2, lng: -51.9 },
    zoom: 4,
    queries: ["Anime Friends", "CCXP", "convenção anime Brasil"],
  },
  {
    country: "mx",
    iso: "mx",
    wikipediaLang: "es",
    acceptLanguage: "es-MX,es;q=0.9,en;q=0.5",
    center: { lat: 23.6, lng: -102.5 },
    zoom: 5,
    queries: ["La Mole", "convención anime México", "Expocon"],
  },
  {
    country: "ar",
    iso: "ar",
    wikipediaLang: "es",
    acceptLanguage: "es-AR,es;q=0.9,en;q=0.5",
    center: { lat: -34.6, lng: -58.4 },
    zoom: 5,
    queries: ["convención anime Argentina", "Comic Con Argentina"],
  },
  {
    country: "cl",
    iso: "cl",
    wikipediaLang: "es",
    acceptLanguage: "es-CL,es;q=0.9,en;q=0.5",
    center: { lat: -33.4, lng: -70.6 },
    zoom: 6,
    queries: ["convención anime Chile", "Santiago Comic Con"],
  },
  {
    country: "co",
    iso: "co",
    wikipediaLang: "es",
    acceptLanguage: "es-CO,es;q=0.9,en;q=0.5",
    center: { lat: 4.7, lng: -74.0 },
    zoom: 6,
    queries: ["convención anime Colombia", "Comic Con Bogotá"],
  },
  {
    country: "pe",
    iso: "pe",
    wikipediaLang: "es",
    acceptLanguage: "es-PE,es;q=0.9,en;q=0.5",
    center: { lat: -12.0, lng: -77.0 },
    zoom: 6,
    queries: ["convención anime Perú", "Comic Con Lima"],
  },
  {
    country: "au",
    iso: "au",
    wikipediaLang: "en",
    acceptLanguage: "en-AU,en;q=0.9",
    center: { lat: -25.3, lng: 133.8 },
    zoom: 4,
    queries: ["SMASH Sydney", "Supanova", "anime convention Australia"],
  },
  {
    country: "nz",
    iso: "nz",
    wikipediaLang: "en",
    acceptLanguage: "en-NZ,en;q=0.9",
    center: { lat: -41.3, lng: 174.8 },
    zoom: 6,
    queries: ["Armageddon Expo", "anime convention New Zealand"],
  },
  {
    country: "fi",
    iso: "fi",
    wikipediaLang: "fi",
    acceptLanguage: "fi-FI,fi;q=0.9,en;q=0.5",
    center: { lat: 61.9, lng: 25.7 },
    zoom: 6,
    queries: ["Tracon", "Animecon Finland", "cosplay tapahtuma"],
  },
  {
    country: "se",
    iso: "se",
    wikipediaLang: "sv",
    acceptLanguage: "sv-SE,sv;q=0.9,en;q=0.5",
    center: { lat: 59.3, lng: 18.1 },
    zoom: 6,
    queries: ["NärCon", "J-Popcon", "manga festival Sverige"],
  },
  {
    country: "no",
    iso: "no",
    wikipediaLang: "no",
    acceptLanguage: "nb-NO,no;q=0.9,en;q=0.5",
    center: { lat: 59.9, lng: 10.7 },
    zoom: 6,
    queries: ["Japan Festival Norway", "anime convention Oslo"],
  },
  {
    country: "dk",
    iso: "dk",
    wikipediaLang: "da",
    acceptLanguage: "da-DK,da;q=0.9,en;q=0.5",
    center: { lat: 55.7, lng: 12.6 },
    zoom: 7,
    queries: ["J-Popcon", "anime convention Denmark"],
  },
  {
    country: "pl",
    iso: "pl",
    wikipediaLang: "pl",
    acceptLanguage: "pl-PL,pl;q=0.9,en;q=0.5",
    center: { lat: 52.2, lng: 21.0 },
    zoom: 6,
    queries: ["Pyrkon", "Festiwal Mangi i Anime", "konwent anime"],
  },
  {
    country: "ro",
    iso: "ro",
    wikipediaLang: "ro",
    acceptLanguage: "ro-RO,ro;q=0.9,en;q=0.5",
    center: { lat: 44.4, lng: 26.1 },
    zoom: 7,
    queries: ["festival anime România", "convenție cosplay"],
  },
  {
    country: "hu",
    iso: "hu",
    wikipediaLang: "hu",
    acceptLanguage: "hu-HU,hu;q=0.9,en;q=0.5",
    center: { lat: 47.5, lng: 19.0 },
    zoom: 7,
    queries: ["AnimeCon Budapest", "képregény fesztivál"],
  },
  {
    country: "cz",
    iso: "cz",
    wikipediaLang: "cs",
    acceptLanguage: "cs-CZ,cs;q=0.9,en;q=0.5",
    center: { lat: 50.1, lng: 14.4 },
    zoom: 7,
    queries: ["Animefest", "festival anime Praha"],
  },
  {
    country: "at",
    iso: "at",
    wikipediaLang: "de",
    acceptLanguage: "de-AT,de;q=0.9,en;q=0.5",
    center: { lat: 48.2, lng: 16.4 },
    zoom: 7,
    queries: ["Anime Festival Wien", "Comic Con Vienna"],
  },
  {
    country: "ch",
    iso: "ch",
    wikipediaLang: "de",
    acceptLanguage: "de-CH,de;q=0.9,fr;q=0.8,en;q=0.5",
    center: { lat: 47.0, lng: 8.5 },
    zoom: 7,
    queries: ["Japan Matsuri", "anime convention Switzerland"],
  },
  {
    country: "nl",
    iso: "nl",
    wikipediaLang: "nl",
    acceptLanguage: "nl-NL,nl;q=0.9,en;q=0.5",
    center: { lat: 52.1, lng: 5.3 },
    zoom: 7,
    queries: ["Abunai", "Animecon Netherlands"],
  },
  {
    country: "be",
    iso: "be",
    wikipediaLang: "nl",
    acceptLanguage: "nl-BE,nl;q=0.9,fr;q=0.8,en;q=0.5",
    center: { lat: 50.8, lng: 4.4 },
    zoom: 8,
    queries: ["Japan Expo Belgium", "convention anime Belgique"],
  },
  {
    country: "pt",
    iso: "pt",
    wikipediaLang: "pt",
    acceptLanguage: "pt-PT,pt;q=0.9,en;q=0.5",
    center: { lat: 38.7, lng: -9.1 },
    zoom: 7,
    queries: ["Iberanime", "convención anime Portugal"],
  },
  {
    country: "gr",
    iso: "gr",
    wikipediaLang: "el",
    acceptLanguage: "el-GR,el;q=0.9,en;q=0.5",
    center: { lat: 37.98, lng: 23.7 },
    zoom: 7,
    queries: ["Comic Con Athens", "φεστιβάλ anime"],
  },
  {
    country: "ua",
    iso: "ua",
    wikipediaLang: "uk",
    acceptLanguage: "uk-UA,uk;q=0.9,en;q=0.5",
    center: { lat: 50.4, lng: 30.5 },
    zoom: 6,
    queries: ["фестиваль аніме", "Comic Con Kyiv"],
  },
  {
    country: "tr",
    iso: "tr",
    wikipediaLang: "tr",
    acceptLanguage: "tr-TR,tr;q=0.9,en;q=0.5",
    center: { lat: 41.0, lng: 29.0 },
    zoom: 6,
    queries: ["anime festivali", "cosplay etkinliği İstanbul"],
  },
  {
    country: "sa",
    iso: "sa",
    wikipediaLang: "ar",
    acceptLanguage: "ar-SA,ar;q=0.9,en;q=0.5",
    center: { lat: 24.7, lng: 46.7 },
    zoom: 6,
    queries: ["مهرجان الأنime", "معرض الكوميك"],
  },
  {
    country: "ae",
    iso: "ae",
    wikipediaLang: "en",
    acceptLanguage: "en-AE,en;q=0.9,ar;q=0.8",
    center: { lat: 25.2, lng: 55.3 },
    zoom: 9,
    queries: ["Middle East Film and Comic Con", "anime convention Dubai"],
  },
  {
    country: "il",
    iso: "il",
    wikipediaLang: "he",
    acceptLanguage: "he-IL,he;q=0.9,en;q=0.8",
    center: { lat: 32.1, lng: 34.8 },
    zoom: 8,
    queries: ["Ani-Fest", "פסטיבל אנימה"],
  },
  {
    country: "za",
    iso: "za",
    wikipediaLang: "en",
    acceptLanguage: "en-ZA,en;q=0.9",
    center: { lat: -26.2, lng: 28.0 },
    zoom: 6,
    queries: ["Comic Con Africa", "anime convention Johannesburg"],
  },
  {
    country: "la",
    iso: "la",
    wikipediaLang: "lo",
    acceptLanguage: "lo-LA,lo;q=0.9,en;q=0.5",
    center: { lat: 17.97, lng: 102.6 },
    zoom: 7,
    queries: ["anime festival Laos", "cosplay"],
  },
  {
    country: "kh",
    iso: "kh",
    wikipediaLang: "en",
    acceptLanguage: "km-KH,km;q=0.9,en;q=0.8",
    center: { lat: 11.56, lng: 104.9 },
    zoom: 9,
    queries: ["anime convention Cambodia", "cosplay Phnom Penh"],
  },
  {
    country: "mm",
    iso: "mm",
    wikipediaLang: "en",
    acceptLanguage: "my-MM,my;q=0.9,en;q=0.8",
    center: { lat: 16.8, lng: 96.2 },
    zoom: 6,
    queries: ["anime festival Myanmar", "comic con Yangon"],
  },
  {
    country: "bn",
    iso: "bn",
    wikipediaLang: "ms",
    acceptLanguage: "ms-BN,ms;q=0.9,en;q=0.8",
    center: { lat: 4.9, lng: 114.9 },
    zoom: 10,
    queries: ["anime convention Brunei"],
  },
];

export function regionByCountry(country: SubcultureEventCountryCode): GlobalDiscoveryRegion | undefined {
  return GLOBAL_DISCOVERY_REGIONS.find((r) => r.country === country);
}

export function regionByIso(iso: string): GlobalDiscoveryRegion | undefined {
  return GLOBAL_DISCOVERY_REGIONS.find((r) => r.iso === iso.toLowerCase());
}

/** Wikipedia/OSM 검색 결과가 서브컬처 행사 관련인지 */
export const SUBCULTURE_RELEVANCE =
  /anime|manga|comic|cosplay|doujin|otaku|comicon|comic-con|maid cafe|メイド|アニメ|漫画|コミ|同人|コスプレ|漫展|动漫|動漫|開拓|コミケ|festival|convention|convención|convencao|festivali|фестиваль|manga|salon|konwent|tapahtuma|mangi|ani-fest|comic con|pop culture|subculture|서브컬처|애니/i;
