/**
 * 국내 상설 메이드 카페 시드 (공개 주소·네이버/나무위키 기준, 2026-07)
 * 영업 여부·위치는 변동될 수 있으니 방문 전 공식 채널 확인.
 */

import type { SubcultureEventSeed } from "@/lib/subculture-event-types";

const OPEN = "2024-01-01T12:00:00+09:00";
const ENDS = "2099-12-31T23:59:59+09:00";

function maid(
  partial: Omit<SubcultureEventSeed, "category" | "startsAt" | "endsAt" | "country"> & {
    startsAt?: string;
  }
): SubcultureEventSeed {
  const { startsAt, ...rest } = partial;
  return {
    ...rest,
    country: "kr",
    category: "maid_cafe",
    startsAt: startsAt ?? OPEN,
    endsAt: ENDS,
  };
}

export const MAID_CAFE_SEEDS: SubcultureEventSeed[] = [
  maid({
    externalKey: "venue-maid-moemoekyun-hapjeong",
    title: "모에모에큥 메이드카페",
    description: "상설 · 합정/상수 · 일본인 메이드",
    venueName: "모에모에큥 메이드카페",
    address: "서울 마포구 독막로6길 16",
    lat: 37.5474108,
    lng: 126.9172952,
    sourceUrl: "https://www.instagram.com/moemoekyung_maidcafe/",
    startsAt: "2023-06-24T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-ohmy-hongdae",
    title: "오! 마이 메이드카페",
    description: "상설 · 홍대 어울마당로",
    venueName: "오! 마이 메이드카페",
    address: "서울 마포구 어울마당로 92",
    lat: 37.5531433,
    lng: 126.9219999,
    sourceUrl: "https://www.instagram.com/ohmy_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-maidmoon-hongdae",
    title: "메이드문 메이드카페 (홍대본점)",
    description: "상설 · 홍대 · 서울·부산 체인",
    venueName: "메이드문 홍대본점",
    address: "서울 마포구 잔다리로6길 34",
    lat: 37.5522194,
    lng: 126.9209507,
    sourceUrl: "https://www.instagram.com/maidmoon_official/",
    startsAt: "2023-01-01T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-loveangel-hongdae",
    title: "러브엔젤 메이드카페",
    description: "상설 · 홍대입구역 인근",
    venueName: "러브엔젤",
    address: "서울 마포구 홍익로6길 38",
    lat: 37.5558558,
    lng: 126.923797,
    sourceUrl: "https://www.instagram.com/loveangel_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-kawaii-hongdae",
    title: "메이드카페 집사카페 카와이 (홍대점)",
    description: "상설 · 메이드·집사 컨셉",
    venueName: "카와이 홍대점",
    address: "서울 마포구 와우산로14길 4",
    lat: 37.5500916,
    lng: 126.9233722,
    sourceUrl: "https://www.instagram.com/kawaii_maidcafe_butlercafe/",
    startsAt: "2024-04-19T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-ayana-hongdae",
    title: "아야나 메이드카페",
    description: "상설 · 홍대",
    venueName: "아야나 메이드카페",
    address: "서울 마포구 와우산로19길 21",
    lat: 37.5512,
    lng: 126.921864,
    sourceUrl: "https://www.instagram.com/ayana_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-maji-tensi-hongdae",
    title: "메이드카페 마지 텐시&데비",
    description: "상설 · 낮 텐시 / 밤 데비",
    venueName: "마지 텐시&데비",
    address: "서울 마포구 와우산로17길 24",
    lat: 37.5503279,
    lng: 126.921658,
    sourceUrl: "https://www.instagram.com/maji_tensi_devi/",
    startsAt: "2024-12-18T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-dolls-hongdae",
    title: "Dolls (돌즈)",
    description: "상설 · 연남 · 성인 전용(주류)",
    venueName: "Dolls",
    address: "서울 마포구 연희로1길 28",
    lat: 37.5602152,
    lng: 126.9255637,
    sourceUrl: "https://www.instagram.com/dolls_kor/",
    startsAt: "2024-10-23T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-dokidoki-hongdae",
    title: "두근두근 메이드카페 (홍대점)",
    description: "상설 · 홍대",
    venueName: "두근두근 홍대점",
    address: "서울 마포구 와우산로21길 20-10",
    lat: 37.5527813,
    lng: 126.9229411,
    sourceUrl: "https://www.instagram.com/doki_doki_maidcafe/",
    startsAt: "2024-12-01T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-maidpia-hongdae",
    title: "메이드피아",
    description: "상설 · 홍대입구역 인근",
    venueName: "메이드피아",
    address: "서울 마포구 와우산로27길 64",
    lat: 37.5553944,
    lng: 126.9252733,
    sourceUrl: "https://www.instagram.com/maidpia_official/",
  }),
  maid({
    externalKey: "venue-maid-maidreamin-hongdae",
    title: "메이드리밍 홍대",
    description: "상설 · 일본 메이드리밍 한국 1호점",
    venueName: "めいどりーみん 弘大店",
    address: "서울 마포구 잔다리로6길 28-1",
    lat: 37.5522169,
    lng: 126.9203449,
    sourceUrl: "https://maidreamin.com/",
    startsAt: "2025-08-09T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-elysion-hongdae",
    title: "엘리시온 메이드카페",
    description: "상설 · 홍대",
    venueName: "엘리시온",
    address: "서울 마포구 와우산로17길 6",
    lat: 37.55024,
    lng: 126.9226954,
    sourceUrl: "https://namu.wiki/w/%EC%97%98%EB%A6%AC%EC%8B%9C%EC%98%A8(%EB%A9%94%EC%9D%B4%EB%93%9C%EC%B9%B4%ED%8E%98)",
    startsAt: "2026-03-12T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-dream-busan",
    title: "드림 메이드카페",
    description: "상설 · 부산 서면",
    venueName: "드림 메이드카페",
    address: "부산 부산진구 중앙대로692번길 46",
    lat: 35.1543148,
    lng: 129.0618196,
    sourceUrl: "https://www.instagram.com/dream_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-maidmoon-busan",
    title: "메이드문 메이드카페 (부산서면점)",
    description: "상설 · 부산 서면",
    venueName: "메이드문 부산서면점",
    address: "부산 부산진구 중앙대로692번길 21",
    lat: 35.1545913,
    lng: 129.0605085,
    sourceUrl: "https://www.instagram.com/maidmoon_busan/",
    startsAt: "2024-04-12T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-kiraring-busan",
    title: "키라링 메이드카페",
    description: "상설 · 부산 전포",
    venueName: "키라링 메이드카페",
    address: "부산 부산진구 전포대로 212",
    lat: 35.1537751,
    lng: 129.0652953,
    sourceUrl: "https://www.instagram.com/kiraring_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-kuroheart-busan",
    title: "쿠로하트 메이드카페",
    description: "상설 · 부산 서면",
    venueName: "쿠로하트",
    address: "부산 부산진구 중앙대로702번길 15",
    lat: 35.1555099,
    lng: 129.0600667,
    sourceUrl: "https://www.instagram.com/kuroheart_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-mochi-busan",
    title: "모찌 메이드카페",
    description: "상설 · 부산 서면 · 코스프레&메이드",
    venueName: "모찌 코스프레&메이드카페",
    address: "부산 부산진구 동천로95번길 8",
    lat: 35.1573217,
    lng: 129.061811,
    sourceUrl: "https://www.instagram.com/mochi_maidcafe/",
    startsAt: "2025-01-15T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-loreley-busan",
    title: "로렐라이 메이드카페",
    description: "상설 · 부산 서면 · 고딕·인형 컨셉",
    venueName: "로렐라이",
    address: "부산 부산진구 중앙대로702번길 27-8",
    lat: 35.1556551,
    lng: 129.0606777,
    sourceUrl: "https://www.instagram.com/loreley_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-gakkou-busan",
    title: "갓코우 토모 메이드카페",
    description: "상설 · 부산 서면 · 학교 컨셉",
    venueName: "갓코우 카페",
    address: "부산 부산진구 서전로68번길 51",
    lat: 35.1537905,
    lng: 129.0672449,
    sourceUrl: "https://www.instagram.com/gakkou_tomo/",
  }),
  maid({
    externalKey: "venue-maid-teitaku-busan",
    title: "테이타쿠 메이드카페",
    description: "상설 · 부산",
    venueName: "테이타쿠",
    address: "부산 부산진구 신천대로62번길 71",
    lat: 35.1525823,
    lng: 129.0584061,
    sourceUrl: "https://www.instagram.com/teitaku_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-you-daegu",
    title: "유 메이드카페",
    description: "상설 · 대구 동성로",
    venueName: "유 메이드카페",
    address: "대구 중구 동성로2길 18-1",
    lat: 35.8677836,
    lng: 128.5966094,
    sourceUrl: "https://www.instagram.com/you_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-naraka-daegu",
    title: "나라카 메이드카페",
    description: "상설 · 대구 동성로",
    venueName: "나라카",
    address: "대구 중구 동성로3길 38",
    lat: 35.8678621,
    lng: 128.5978869,
    sourceUrl: "https://www.instagram.com/naraka_maidcafe/",
  }),
];
