/**
 * 상설 메이드 카페 시드 (공개 주소 기준, 2026-07)
 * - KR: 홍대·부산·대구 등
 * - JP/TH/TW: `subculture-maid-cafe-seeds-international.ts`
 * 영업 여부·위치는 변동될 수 있으니 방문 전 공식 채널 확인.
 */

import { INTERNATIONAL_MAID_CAFE_SEEDS } from "@/lib/subculture-maid-cafe-seeds-international";
import type { SubcultureEventSeed } from "@/lib/subculture-event-types";

const OPEN = "2024-01-01T12:00:00+09:00";
const ENDS = "2099-12-31T23:59:59+09:00";

function maid(
  partial: Omit<SubcultureEventSeed, "category" | "startsAt" | "endsAt" | "country"> & {
    startsAt?: string;
  }
): SubcultureEventSeed {
  const { startsAt, ...rest } = partial;
  return {
    ...rest,
    country: "kr",
    category: "maid_cafe",
    startsAt: startsAt ?? OPEN,
    endsAt: ENDS,
  };
}

export const KR_MAID_CAFE_SEEDS: SubcultureEventSeed[] = [
  maid({
    externalKey: "venue-maid-moemoekyun-hapjeong",
    title: "Moemoe Kyun Maid Cafe",
    description: "Permanent · Hapjeong/Sangsu · Japanese maids",
    venueName: "Moemoe Kyun Maid Cafe",
    address: "16 Dokmak-ro 6-gil, Mapo-gu, Seoul",
    lat: 37.5474108,
    lng: 126.9172952,
    sourceUrl: "https://www.instagram.com/moemoekyung_maidcafe/",
    startsAt: "2023-06-24T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-ohmy-hongdae",
    title: "Oh My Maid Cafe",
    description: "Permanent · Hongdae Eoulmadang-ro",
    venueName: "Oh My Maid Cafe",
    address: "92 Eoulmadang-ro, Mapo-gu, Seoul",
    lat: 37.5531433,
    lng: 126.9219999,
    sourceUrl: "https://www.instagram.com/ohmy_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-maidmoon-hongdae",
    title: "Maid Moon Maid Cafe (Hongdae main)",
    description: "Permanent · Hongdae · Seoul & Busan chain",
    venueName: "Maid Moon Hongdae main",
    address: "34 Jandari-ro 6-gil, Mapo-gu, Seoul",
    lat: 37.5522194,
    lng: 126.9209507,
    sourceUrl: "https://www.instagram.com/maidmoon_official/",
    startsAt: "2023-01-01T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-loveangel-hongdae",
    title: "Love Angel Maid Cafe",
    description: "Permanent · near Hongdae Station",
    venueName: "Love Angel",
    address: "38 Hongik-ro 6-gil, Mapo-gu, Seoul",
    lat: 37.5558558,
    lng: 126.923797,
    sourceUrl: "https://www.instagram.com/loveangel_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-kawaii-hongdae",
    title: "Maid Cafe Butler Cafe Kawaii (Hongdae)",
    description: "Permanent · maid & butler concept",
    venueName: "Kawaii Hongdae",
    address: "4 Wausan-ro 14-gil, Mapo-gu, Seoul",
    lat: 37.5500916,
    lng: 126.9233722,
    sourceUrl: "https://www.instagram.com/kawaii_maidcafe_butlercafe/",
    startsAt: "2024-04-19T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-ayana-hongdae",
    title: "Ayana Maid Cafe",
    description: "Permanent · Hongdae",
    venueName: "Ayana Maid Cafe",
    address: "21 Wausan-ro 19-gil, Mapo-gu, Seoul",
    lat: 37.5512,
    lng: 126.921864,
    sourceUrl: "https://www.instagram.com/ayana_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-maji-tensi-hongdae",
    title: "Maid Cafe Maji Tenshi & Debby",
    description: "Permanent · angel by day / devil by night",
    venueName: "Maji Tenshi & Debby",
    address: "24 Wausan-ro 17-gil, Mapo-gu, Seoul",
    lat: 37.5503279,
    lng: 126.921658,
    sourceUrl: "https://www.instagram.com/maji_tensi_devi/",
    startsAt: "2024-12-18T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-dolls-hongdae",
    title: "Dolls",
    description: "Permanent · Yeonnam · adults only (alcohol served)",
    venueName: "Dolls",
    address: "28 Yeonhui-ro 1-gil, Mapo-gu, Seoul",
    lat: 37.5602152,
    lng: 126.9255637,
    sourceUrl: "https://www.instagram.com/dolls_kor/",
    startsAt: "2024-10-23T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-dokidoki-hongdae",
    title: "Dugeundugeun Maid Cafe (Hongdae)",
    description: "Permanent · Hongdae",
    venueName: "Dugeundugeun Hongdae",
    address: "20-10 Wausan-ro 21-gil, Mapo-gu, Seoul",
    lat: 37.5527813,
    lng: 126.9229411,
    sourceUrl: "https://www.instagram.com/doki_doki_maidcafe/",
    startsAt: "2024-12-01T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-maidpia-hongdae",
    title: "Maid Pia",
    description: "Permanent · near Hongdae Station",
    venueName: "Maid Pia",
    address: "64 Wausan-ro 27-gil, Mapo-gu, Seoul",
    lat: 37.5553944,
    lng: 126.9252733,
    sourceUrl: "https://www.instagram.com/maidpia_official/",
  }),
  maid({
    externalKey: "venue-maid-maidreamin-hongdae",
    title: "Maidreaming Hongdae",
    description: "Permanent · Japan Maidreaming Korea flagship",
    venueName: "めいどりーみん 弘大店",
    address: "28-1 Jandari-ro 6-gil, Mapo-gu, Seoul",
    lat: 37.5522169,
    lng: 126.9203449,
    sourceUrl: "https://maidreamin.com/",
    startsAt: "2025-08-09T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-elysion-hongdae",
    title: "Elysion Maid Cafe",
    description: "Permanent · Hongdae",
    venueName: "Elysion",
    address: "6 Wausan-ro 17-gil, Mapo-gu, Seoul",
    lat: 37.55024,
    lng: 126.9226954,
    sourceUrl: "https://namu.wiki/w/%EC%97%98%EB%A6%AC%EC%8B%9C%EC%98%A8(%EB%A9%94%EC%9D%B4%EB%93%9C%EC%B9%B4%ED%8E%98)",
    startsAt: "2026-03-12T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-dream-busan",
    title: "Dream Maid Cafe",
    description: "Permanent · Busan Seomyeon",
    venueName: "Dream Maid Cafe",
    address: "46 Jungang-daero 692beon-gil, Busanjin-gu, Busan",
    lat: 35.1543148,
    lng: 129.0618196,
    sourceUrl: "https://www.instagram.com/dream_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-maidmoon-busan",
    title: "Maid Moon Maid Cafe (Busan Seomyeon)",
    description: "Permanent · Busan Seomyeon",
    venueName: "Maid Moon Busan Seomyeon",
    address: "21 Jungang-daero 692beon-gil, Busanjin-gu, Busan",
    lat: 35.1545913,
    lng: 129.0605085,
    sourceUrl: "https://www.instagram.com/maidmoon_busan/",
    startsAt: "2024-04-12T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-kiraring-busan",
    title: "Kirarin Maid Cafe",
    description: "Permanent · Busan Jeonpo",
    venueName: "Kirarin Maid Cafe",
    address: "212 Jeonpo-daero, Busanjin-gu, Busan",
    lat: 35.1537751,
    lng: 129.0652953,
    sourceUrl: "https://www.instagram.com/kiraring_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-kuroheart-busan",
    title: "Kuroheart Maid Cafe",
    description: "Permanent · Busan Seomyeon",
    venueName: "Kuroheart",
    address: "15 Jungang-daero 702beon-gil, Busanjin-gu, Busan",
    lat: 35.1555099,
    lng: 129.0600667,
    sourceUrl: "https://www.instagram.com/kuroheart_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-mochi-busan",
    title: "Mochi Maid Cafe",
    description: "Permanent · Busan Seomyeon · cosplay & maid",
    venueName: "Mochi Cosplay & Maid Cafe",
    address: "8 Dongcheon-ro 95beon-gil, Busanjin-gu, Busan",
    lat: 35.1573217,
    lng: 129.061811,
    sourceUrl: "https://www.instagram.com/mochi_maidcafe/",
    startsAt: "2025-01-15T12:00:00+09:00",
  }),
  maid({
    externalKey: "venue-maid-loreley-busan",
    title: "Lorelei Maid Cafe",
    description: "Permanent · Busan Seomyeon · gothic doll theme",
    venueName: "Lorelei",
    address: "27-8 Jungang-daero 702beon-gil, Busanjin-gu, Busan",
    lat: 35.1556551,
    lng: 129.0606777,
    sourceUrl: "https://www.instagram.com/loreley_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-gakkou-busan",
    title: "Gakkou Tomo Maid Cafe",
    description: "Permanent · Busan Seomyeon · school theme",
    venueName: "Gakkou Cafe",
    address: "51 Seojeon-ro 68beon-gil, Busanjin-gu, Busan",
    lat: 35.1537905,
    lng: 129.0672449,
    sourceUrl: "https://www.instagram.com/gakkou_tomo/",
  }),
  maid({
    externalKey: "venue-maid-teitaku-busan",
    title: "Otaku Maid Cafe",
    description: "Permanent · Busan",
    venueName: "Otaku",
    address: "71 Sincheon-daero 62beon-gil, Busanjin-gu, Busan",
    lat: 35.1525823,
    lng: 129.0584061,
    sourceUrl: "https://www.instagram.com/teitaku_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-you-daegu",
    title: "Yu Maid Cafe",
    description: "Permanent · Daegu Dongseong-ro",
    venueName: "Yu Maid Cafe",
    address: "18-1 Dongseong-ro 2-gil, Jung-gu, Daegu",
    lat: 35.8677836,
    lng: 128.5966094,
    sourceUrl: "https://www.instagram.com/you_maidcafe/",
  }),
  maid({
    externalKey: "venue-maid-naraka-daegu",
    title: "Naraka Maid Cafe",
    description: "Permanent · Daegu Dongseong-ro",
    venueName: "Naraka",
    address: "38 Dongseong-ro 3-gil, Jung-gu, Daegu",
    lat: 35.8678621,
    lng: 128.5978869,
    sourceUrl: "https://www.instagram.com/naraka_maidcafe/",
  }),
];

export const MAID_CAFE_SEEDS: SubcultureEventSeed[] = [
  ...KR_MAID_CAFE_SEEDS,
  ...INTERNATIONAL_MAID_CAFE_SEEDS,
];
