-- MocoDonationType: SFX
ALTER TYPE "MocoDonationType" ADD VALUE IF NOT EXISTS 'SFX';

ALTER TABLE "VoiceChannel" ADD COLUMN IF NOT EXISTS "videoDonationRateMocoPerSec" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "VoiceChannel" ADD COLUMN IF NOT EXISTS "videoDonationMinMoco" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "VoiceChannel" ADD COLUMN IF NOT EXISTS "videoDonationBlocklistJson" JSONB;

ALTER TABLE "MocoDonation" ADD COLUMN IF NOT EXISTS "sfxKey" TEXT;
ALTER TABLE "MocoDonation" ADD COLUMN IF NOT EXISTS "videoTitle" TEXT;
ALTER TABLE "MocoDonation" ADD COLUMN IF NOT EXISTS "startSec" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MocoDonation" ADD COLUMN IF NOT EXISTS "endSec" INTEGER;
ALTER TABLE "MocoDonation" ADD COLUMN IF NOT EXISTS "playToEnd" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MocoDonation" ADD COLUMN IF NOT EXISTS "segmentPlaySec" INTEGER;
