import type { WikiTitle } from "@/lib/wiki/editorUtils";

export const DUMMY_WIKI_TITLES: WikiTitle[] = [
  { id: "chiikawa", original: "ちいかわ", english: "Chiikawa: Something Small and Cute" },
  { id: "chiikawa-short", original: "ちいかわ", english: "Chiikawa" },
  { id: "chiikawa-something", original: "ちいかわ", english: "Chiikawa: Something" },
  { id: "chiikawa-small", original: "ちいかわ なんか小さくてかわいいやつ", english: "Chiikawa: Something Small" },
  { id: "chiikawa-party", original: "ちいかわパーティー", english: "Chiikawa Party" },
  { id: "chiikawa-movie", original: "映画 ちいかわ", english: "Chiikawa: The Movie" },
  { id: "hachiware", original: "ハチワレ", english: "Hachiware: Chiikawa Friend" },
  { id: "usagi", original: "うさぎ", english: "Usagi: Something Wild" },
  { id: "frieren", original: "葬送のフリーレン", english: "Frieren: Beyond Journey's End" },
  { id: "frieren-short", original: "フリーレン", english: "Frieren" },
  { id: "aot", original: "進撃の巨人", english: "Attack on Titan" },
  { id: "aot-final", original: "進撃の巨人 The Final Season", english: "Attack on Titan: The Final Season" },
  { id: "aot-junior", original: "進撃！巨人中学校", english: "Attack on Titan: Junior High" },
  { id: "demon-slayer", original: "鬼滅の刃", english: "Demon Slayer: Kimetsu no Yaiba" },
  { id: "demon-slayer-mugen", original: "鬼滅の刃 無限列車編", english: "Demon Slayer: Mugen Train" },
  { id: "jujutsu", original: "呪術廻戦", english: "Jujutsu Kaisen" },
  { id: "jujutsu-0", original: "劇場版 呪術廻戦 0", english: "Jujutsu Kaisen 0" },
  { id: "spy-family", original: "SPY×FAMILY", english: "SPY x FAMILY" },
  { id: "spy-family-code", original: "SPY×FAMILY CODE: White", english: "SPY x FAMILY Code: White" },
  { id: "one-piece", original: "ONE PIECE", english: "One Piece" },
  { id: "one-piece-red", original: "ONE PIECE FILM RED", english: "One Piece Film: Red" },
  { id: "naruto", original: "NARUTO", english: "Naruto" },
  { id: "naruto-shippuden", original: "NARUTO -ナルト- 疾風伝", english: "Naruto Shippuden" },
  { id: "chainsaw", original: "チェンソーマン", english: "Chainsaw Man" },
  { id: "oshi-no-ko", original: "【推しの子】", english: "Oshi no Ko" },
  { id: "bocchi", original: "ぼっち・ざ・ろっく！", english: "Bocchi the Rock!" },
  { id: "k-on", original: "けいおん！", english: "K-On!" },
  { id: "your-name", original: "君の名は。", english: "Your Name." },
  { id: "suzume", original: "すずめの戸締まり", english: "Suzume" },
  { id: "weathering", original: "天気の子", english: "Weathering With You" },
  { id: "haikyu", original: "ハイキュー!!", english: "Haikyu!!" },
  { id: "blue-lock", original: "ブルーロック", english: "Blue Lock" },
  { id: "dungeon-meshi", original: "ダンジョン飯", english: "Delicious in Dungeon" },
  { id: "apoa", original: "葬送のフリーレン 番外", english: "Frieren: Prelude" },
];
