version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: mocomo-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mocomo
    ports:
      - "5432:5432"
    volumes:
      - mocomo_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mocomo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mocomo_pgdata:
