/** Culture wiki copy — use with `useI18n().u`. */
export function animeUi(u: (ko: string, en: string) => string) {
  return {
    back: u("뒤로", "Back"),
    work: u("작품", "Work"),
    loadError: u("작품을 불러오지 못했습니다.", "Could not load work."),
    retry: u("다시 시도", "Try again"),
    starFail: u("STAR 저장에 실패했습니다.", "Could not save to STAR."),
    overview: u("개요", "Overview"),
    characters: u("등장인물", "Characters"),
    infoboxCategory: u("분류", "Category"),
    studio: u("스튜디오", "Studio"),
    tags: u("태그", "Tags"),
    historyA11y: u("수정 기록", "Edit history"),
    editA11y: u("문서 편집", "Edit article"),
    loginRequired: u("로그인 필요", "Sign in required"),
    editLoginMsg: u("편집은 로그인 후 이용할 수 있습니다.", "Sign in to edit."),
    starLoginMsg: u("STAR 저장은 로그인 후 이용할 수 있습니다.", "Sign in to save to STAR."),
    starRemoveA11y: u("STAR 해제", "Remove STAR"),
    starAddA11y: u("STAR 저장", "Save to STAR"),
    author: (username: string) => u(`작성자 @${username}`, `By @${username}`),
    createdAt: (s: string) => u(`최초 등록 ${s}`, `Created ${s}`),
    updatedAt: (s: string) => u(`마지막 수정 ${s}`, `Updated ${s}`),
    edit: u("편집", "Edit"),
    history: u("수정 기록", "History"),
    toc: u("목차", "Contents"),
    emptyBody: u("등록된 본문이 없습니다.", "No article body yet."),
    defaultInfoboxTitle: u("작품 정보", "Work info"),
    imageAlt: u("이미지", "Image"),
    collapseClose: u("접기", "Collapse"),
    collapseOpen: u("스포일러 · 탭하여 펼치기", "Spoiler · tap to expand"),
    historyTitle: u("수정 기록", "Edit history"),
    historyLoadError: u("수정 기록을 불러오지 못했습니다.", "Could not load history."),
    historyHint: u("시간 순 · 유저 아이디 · 날짜", "Newest first · user · date"),
    editSummaryDefault: u("내용 수정", "Content edit"),
    restoreConfirmTitle: u("이 버전으로 복구", "Restore this version"),
    restoreConfirmMsg: u("문서를 이 시점으로 되돌릴까요?", "Restore the article to this point?"),
    cancel: u("취소", "Cancel"),
    restore: u("복구", "Restore"),
    restoreDoneTitle: u("복구 완료", "Restored"),
    restoreDoneMsg: u("선택한 버전으로 되돌렸습니다.", "Restored to the selected version."),
    restoreFailTitle: u("복구 실패", "Restore failed"),
    restoreFail: u("복구하지 못했습니다.", "Could not restore."),
    formEditTitle: u("문서 편집", "Edit article"),
    formCreateTitle: u("작품 등록", "Add work"),
    formIntro: u(
      "로그인한 누구나 작품 문서를 등록·수정할 수 있습니다. 저장하면 컬쳐 위키에 바로 반영됩니다.",
      "Signed-in users can add or edit work articles. Saves apply to Culture Wiki immediately."
    ),
    titleLabel: u("제목 *", "Title *"),
    titlePh: u("한글 제목", "Title"),
    titleEnLabel: u("영문 제목", "English title"),
    genreLabel: u("장르 *", "Genre *"),
    coverLabel: u("표지 이미지", "Cover image"),
    coverUploadA11y: u("표지 이미지 업로드", "Upload cover"),
    coverUpload: u("사진 업로드", "Upload photo"),
    bannerLabel: u("배너 이미지", "Banner image"),
    bannerUploadA11y: u("배너 이미지 업로드", "Upload banner"),
    bannerUpload: u("배너 사진 업로드", "Upload banner photo"),
    studioLabel: u("제작사", "Studio"),
    studioPh: u("스튜디오 · 제작사", "Studio · production"),
    infoboxLabel: u("작품 정보표", "Infobox"),
    infoboxPh: u("=== 작품 정보 ===\n장르 | 액션\n감독 | ...", "=== Work info ===\nGenre | Action\nDirector | ..."),
    synopsisLabel: u("줄거리 / 설명", "Synopsis / description"),
    photoUploadBtn: u("사진 업로드", "Upload photo"),
    videoPh: u("영상 링크 붙여넣기 (유튜브)", "Paste video link (YouTube)"),
    insertBtn: u("넣기", "Insert"),
    synopsisPh: u(
      "작품 소개. 사진은 업로드, 영상은 링크를 붙여넣으세요.",
      "Describe the work. Upload photos or paste video links."
    ),
    preview: u("미리보기", "Preview"),
    worldLabel: u("세계관", "World"),
    worldPh: u("세계관 · 설정", "World · setting"),
    castLabel: u("등장인물 (한 줄에 한 명)", "Characters (one per line)"),
    castPh: u("캐릭터 이름\n한 줄에 하나씩", "Character name\nOne per line"),
    tagsLabel: u("태그 (쉼표 구분)", "Tags (comma-separated)"),
    tagsPh: u("예: 2024, TV, 인기", "e.g. 2024, TV, popular"),
    summaryLabel: u("수정 요약 (선택)", "Edit summary (optional)"),
    summaryPh: u("예: 줄거리 보강, 오타 수정", "e.g. expanded synopsis, typo fix"),
    licenseNote: u(
      "컬쳐 위키 글은 CC BY-NC-SA 4.0로 공유됩니다. 저작권·명예훼손에 유의해 주세요. 자세한 내용은 설정의 이용 약관에서 확인할 수 있습니다.",
      "Culture Wiki articles are shared under CC BY-NC-SA 4.0. Respect copyright and defamation rules. See Terms in Settings for details."
    ),
    saving: u("저장 중…", "Saving…"),
    saveEdit: u("수정 저장", "Save changes"),
    saveCreate: u("등록하기", "Publish"),
    photoLibPerm: u("사진 라이브러리 접근 권한이 필요합니다.", "Photo library access is required."),
    saveDoneTitle: u("수정 완료", "Saved"),
    saveCreateDoneTitle: u("등록 완료", "Published"),
    saveDoneMsg: u("컬쳐 위키에 반영되었습니다.", "Applied to Culture Wiki."),
    saveFailTitle: u("저장 실패", "Save failed"),
    saveFailDefault: u("저장에 실패했습니다.", "Could not save."),
    coverFail: u("표지를 올리지 못했습니다.", "Could not upload cover."),
    bannerFail: u("배너를 올리지 못했습니다.", "Could not upload banner."),
    photoFail: u("사진을 올리지 못했습니다.", "Could not upload photo."),
    inputCheckTitle: u("입력 확인", "Check input"),
    videoLinkRequired: u("영상 링크를 붙여넣어 주세요.", "Paste a video link."),
    youtubeRequired: u("유튜브 링크를 붙여넣어 주세요.", "Paste a YouTube link."),
    titleRequired: u("제목을 입력해 주세요.", "Enter a title."),
    photoCaption: u("사진", "Photo"),
  };
}

export type AnimeUi = ReturnType<typeof animeUi>;
