import type { TFn } from "@/i18n/types";

/** Culture wiki copy — use with `useI18n().t`. */
export function animeUi(t: TFn) {
  return {
    back: t("m.common.back"),
    work: t("m.anime.work"),
    loadError: t("m.anime.could_not_load_work"),
    retry: t("m.common.try_again"),
    starFail: t("m.anime.could_not_save_to_star"),
    overview: t("m.anime.overview"),
    characters: t("m.anime.characters"),
    infoboxCategory: t("m.common.category"),
    studio: t("m.anime.studio"),
    tags: t("m.anime.tags"),
    historyA11y: t("m.anime.edit_history"),
    editA11y: t("m.anime.edit_article"),
    loginRequired: t("m.common.sign_in_required"),
    editLoginMsg: t("m.anime.sign_in_to_edit"),
    starLoginMsg: t("m.common.sign_in_to_save_to_star"),
    starRemoveA11y: t("m.anime.remove_star"),
    starAddA11y: t("m.common.save_to_star"),
    author: (username: string) => t("m.anime.by_username", { username: String(username) }),
    createdAt: (s: string) => t("m.anime.created_s", { s: String(s) }),
    updatedAt: (s: string) => t("m.anime.updated_s", { s: String(s) }),
    edit: t("m.common.edit"),
    history: t("m.anime.history"),
    toc: t("m.anime.contents"),
    emptyBody: t("m.anime.no_article_body_yet"),
    defaultInfoboxTitle: t("m.anime.work_info"),
    imageAlt: t("m.anime.image"),
    collapseClose: t("m.anime.collapse"),
    collapseOpen: t("m.anime.spoiler_tap_to_expand"),
    historyTitle: t("m.anime.edit_history"),
    historyLoadError: t("m.anime.could_not_load_history"),
    historyHint: t("m.anime.newest_first_user_date"),
    editSummaryDefault: t("m.anime.content_edit"),
    restoreConfirmTitle: t("m.anime.restore_this_version"),
    restoreConfirmMsg: t("m.anime.restore_the_article_to_this_point"),
    cancel: t("m.common.cancel"),
    restore: t("m.anime.restore"),
    restoreDoneTitle: t("m.anime.restored"),
    restoreDoneMsg: t("m.anime.restored_to_the_selected_version"),
    restoreFailTitle: t("m.anime.restore_failed"),
    restoreFail: t("m.anime.could_not_restore"),
    formEditTitle: t("m.anime.edit_article"),
    formCreateTitle: t("m.anime.add_work"),
    formIntro: t("m.anime.signed_in_users_can_add_or"),
    englishOnlyNotice: t("wiki.form.englishOnlyNotice"),
    titleLabel: t("m.anime.title"),
    titlePh: t("m.common.title"),
    titleEnLabel: t("m.anime.english_title"),
    titleEnPh: t("wiki.form.titleEnPlaceholder"),
    genreLabel: t("m.anime.genre"),
    coverLabel: t("m.anime.cover_image"),
    coverUploadA11y: t("m.anime.upload_cover"),
    coverUpload: t("m.common.upload_photo"),
    bannerLabel: t("m.anime.banner_image"),
    bannerUploadA11y: t("m.anime.upload_banner"),
    bannerUpload: t("m.anime.upload_banner_photo"),
    studioLabel: t("m.anime.studio"),
    studioPh: t("m.anime.studio_production"),
    infoboxLabel: t("m.anime.infobox"),
    infoboxPh: t("m.anime.work_info_genre_action_director"),
    synopsisLabel: t("m.anime.synopsis_description"),
    photoUploadBtn: t("m.common.upload_photo"),
    videoPh: t("m.anime.paste_video_link_youtube"),
    insertBtn: t("m.anime.insert"),
    synopsisPh: t("m.anime.describe_the_work_upload_photos_or"),
    preview: t("m.common.preview"),
    worldLabel: t("m.anime.world"),
    worldPh: t("m.anime.world_setting"),
    castLabel: t("m.anime.characters_one_per_line"),
    castPh: t("m.anime.character_name_one_per_line"),
    tagsLabel: t("m.anime.tags_comma_separated"),
    tagsPh: t("m.anime.e_g_2024_tv_popular"),
    summaryLabel: t("m.anime.edit_summary_optional"),
    summaryPh: t("m.anime.e_g_expanded_synopsis_typo_fix"),
    licenseNote: t("m.anime.culture_wiki_articles_are_shared_under"),
    saving: t("m.common.saving"),
    saveEdit: t("m.anime.save_changes"),
    saveCreate: t("m.anime.publish"),
    photoLibPerm: t("m.common.photo_library_access_is_required"),
    saveDoneTitle: t("m.common.saved"),
    saveCreateDoneTitle: t("m.anime.published"),
    saveDoneMsg: t("m.anime.applied_to_culture_wiki"),
    saveFailTitle: t("m.anime.save_failed"),
    saveFailDefault: t("m.common.could_not_save"),
    coverFail: t("m.anime.could_not_upload_cover"),
    bannerFail: t("m.common.could_not_upload_banner"),
    photoFail: t("m.anime.could_not_upload_photo"),
    inputCheckTitle: t("m.anime.check_input"),
    videoLinkRequired: t("m.anime.paste_a_video_link"),
    youtubeRequired: t("m.anime.paste_a_youtube_link"),
    titleRequired: t("m.common.enter_a_title"),
    photoCaption: t("m.common.photo"),
  };
}

export type AnimeUi = ReturnType<typeof animeUi>;
