/** @deprecated Apick 1원 계좌 인증 — bank-verification.ts 사용 */
export {
  getBankVerificationStatus as getPhoneVerificationStatus,
  clearUsedMarketBankPending as clearUsedMarketPhonePending,
  sendUsedMarketPhoneOtp,
  verifyUsedMarketPhoneOtp,
  sendSellerPhoneOtp,
  verifySellerPhoneOtp,
  sendSellerSignupPhoneOtp,
  verifySellerSignupPhoneOtp,
  getBankVerificationStatus,
  clearUsedMarketBankPending,
  clearAccountBankPending,
  sendAccountBankVerification,
  verifyAccountBankCode,
  sendUsedMarketBankVerification,
  verifyUsedMarketBankCode,
  sendSellerBankVerification,
  verifySellerBankCode,
} from "@/actions/bank-verification";
