import type { VRMHumanBoneName } from "@pixiv/three-vrm-core";

/** BVH/FBX/Mixamo 유사 본명 → VRM Humanoid */
export const MOCAP_TO_VRM: Record<string, VRMHumanBoneName> = {
  hips: "hips",
  hip: "hips",
  pelvis: "hips",
  root: "hips",
  spine: "spine",
  spine1: "chest",
  spine2: "upperChest",
  spine3: "upperChest",
  chest: "chest",
  upperchest: "upperChest",
  neck: "neck",
  head: "head",
  leftshoulder: "leftShoulder",
  lshoulder: "leftShoulder",
  leftuparm: "leftUpperArm",
  leftarm: "leftUpperArm",
  lupperarm: "leftUpperArm",
  leftforearm: "leftLowerArm",
  leftlowerarm: "leftLowerArm",
  lforearm: "leftLowerArm",
  lefthand: "leftHand",
  lhand: "leftHand",
  rightshoulder: "rightShoulder",
  rshoulder: "rightShoulder",
  rightuparm: "rightUpperArm",
  rightarm: "rightUpperArm",
  rupperarm: "rightUpperArm",
  rightforearm: "rightLowerArm",
  rightlowerarm: "rightLowerArm",
  rforearm: "rightLowerArm",
  righthand: "rightHand",
  rhand: "rightHand",
  leftupleg: "leftUpperLeg",
  leftleg: "leftUpperLeg",
  lupperleg: "leftUpperLeg",
  leftlowleg: "leftLowerLeg",
  leftlowerleg: "leftLowerLeg",
  llowerleg: "leftLowerLeg",
  leftfoot: "leftFoot",
  lfoot: "leftFoot",
  lefttoe: "leftToes",
  rightupleg: "rightUpperLeg",
  rightleg: "rightUpperLeg",
  rupperleg: "rightUpperLeg",
  rightlowleg: "rightLowerLeg",
  rightlowerleg: "rightLowerLeg",
  rlowerleg: "rightLowerLeg",
  rightfoot: "rightFoot",
  rfoot: "rightFoot",
  righttoe: "rightToes",
  mixamorighips: "hips",
  mixamorigspine: "spine",
  mixamorigspine1: "chest",
  mixamorigspine2: "upperChest",
  mixamorigneck: "neck",
  mixamorighead: "head",
  mixamorigleftshoulder: "leftShoulder",
  mixamorigleftarm: "leftUpperArm",
  mixamorigleftforearm: "leftLowerArm",
  mixamoriglefthand: "leftHand",
  mixamorigrightshoulder: "rightShoulder",
  mixamorigrightarm: "rightUpperArm",
  mixamorigrightforearm: "rightLowerArm",
  mixamorigrighthand: "rightHand",
  mixamorigleftupleg: "leftUpperLeg",
  mixamorigleftleg: "leftLowerLeg",
  mixamorigleftfoot: "leftFoot",
  mixamorigrightupleg: "rightUpperLeg",
  mixamorigrightleg: "rightLowerLeg",
  mixamorigrightfoot: "rightFoot",
};

export function normalizeMocapBoneName(raw: string): string {
  return raw.replace(/[^a-zA-Z0-9]/g, "").toLowerCase();
}

export function mapMocapBone(raw: string): VRMHumanBoneName | null {
  const key = normalizeMocapBoneName(raw);
  return MOCAP_TO_VRM[key] ?? null;
}
