import type { Locale } from "@/lib/i18n/config";

/** NLLB-200 FLORES-200 language codes used by Xenova/nllb-200-distilled-600M. */
export type NllbCode = string;

/** MoCoMo UI locale → NLLB target language code. */
export const LOCALE_TO_NLLB: Record<Locale, NllbCode> = {
  ko: "kor_Hang",
  en: "eng_Latn",
  ja: "jpn_Jpan",
  zh: "zho_Hans",
  "zh-TW": "zho_Hant",
  el: "ell_Grek",
  fr: "fra_Latn",
  de: "deu_Latn",
  es: "spa_Latn",
  pt: "por_Latn",
  "pt-BR": "por_Latn",
  it: "ita_Latn",
  nl: "nld_Latn",
  pl: "pol_Latn",
  ru: "rus_Cyrl",
  uk: "ukr_Cyrl",
  ar: "arb_Arab",
  he: "heb_Hebr",
  tr: "tur_Latn",
  fa: "pes_Arab",
  hi: "hin_Deva",
  bn: "ben_Beng",
  ta: "tam_Taml",
  te: "tel_Telu",
  mr: "mar_Deva",
  ur: "urd_Arab",
  th: "tha_Thai",
  vi: "vie_Latn",
  id: "ind_Latn",
  ms: "zsm_Latn",
  fil: "tgl_Latn",
  sw: "swh_Latn",
  sv: "swe_Latn",
  no: "nob_Latn",
  da: "dan_Latn",
  fi: "fin_Latn",
  cs: "ces_Latn",
  sk: "slk_Latn",
  hu: "hun_Latn",
  ro: "ron_Latn",
  bg: "bul_Cyrl",
  hr: "hrv_Latn",
  sr: "srp_Cyrl",
  sl: "slv_Latn",
  lt: "lit_Latn",
  lv: "lvs_Latn",
  et: "est_Latn",
  sq: "als_Latn",
  mk: "mkd_Cyrl",
  ca: "cat_Latn",
  eu: "eus_Latn",
  gl: "glg_Latn",
  is: "isl_Latn",
  ga: "gle_Latn",
  cy: "cym_Latn",
  af: "afr_Latn",
  am: "amh_Ethi",
  az: "azj_Latn",
  be: "bel_Cyrl",
  bs: "bos_Latn",
  ka: "kat_Geor",
  kk: "kaz_Cyrl",
  km: "khm_Khmr",
  lo: "lao_Laoo",
  mn: "khk_Cyrl",
  my: "mya_Mymr",
  ne: "npi_Deva",
  si: "sin_Sinh",
  uz: "uzn_Latn",
  hy: "hye_Armn",
  mt: "mlt_Latn",
  lb: "ltz_Latn",
  pa: "pan_Guru",
  ha: "hau_Latn",
  yo: "yor_Latn",
  ig: "ibo_Latn",
  zu: "zul_Latn",
  eo: "epo_Latn",
};

/** ISO 639-3 (franc) → NLLB code for source detection. */
export const ISO6393_TO_NLLB: Record<string, NllbCode> = {
  kor: "kor_Hang",
  eng: "eng_Latn",
  jpn: "jpn_Jpan",
  cmn: "zho_Hans",
  zho: "zho_Hans",
  ell: "ell_Grek",
  fra: "fra_Latn",
  deu: "deu_Latn",
  spa: "spa_Latn",
  por: "por_Latn",
  ita: "ita_Latn",
  nld: "nld_Latn",
  pol: "pol_Latn",
  rus: "rus_Cyrl",
  ukr: "ukr_Cyrl",
  arb: "arb_Arab",
  ara: "arb_Arab",
  heb: "heb_Hebr",
  tur: "tur_Latn",
  pes: "pes_Arab",
  fas: "pes_Arab",
  hin: "hin_Deva",
  ben: "ben_Beng",
  tam: "tam_Taml",
  tel: "tel_Telu",
  mar: "mar_Deva",
  urd: "urd_Arab",
  tha: "tha_Thai",
  vie: "vie_Latn",
  ind: "ind_Latn",
  zsm: "zsm_Latn",
  msa: "zsm_Latn",
  tgl: "tgl_Latn",
  fil: "tgl_Latn",
  swh: "swh_Latn",
  swe: "swe_Latn",
  nob: "nob_Latn",
  nor: "nob_Latn",
  dan: "dan_Latn",
  fin: "fin_Latn",
  ces: "ces_Latn",
  slk: "slk_Latn",
  hun: "hun_Latn",
  ron: "ron_Latn",
  bul: "bul_Cyrl",
  hrv: "hrv_Latn",
  srp: "srp_Cyrl",
  slv: "slv_Latn",
  lit: "lit_Latn",
  lvs: "lvs_Latn",
  lav: "lvs_Latn",
  est: "est_Latn",
  als: "als_Latn",
  sqi: "als_Latn",
  mkd: "mkd_Cyrl",
  cat: "cat_Latn",
  eus: "eus_Latn",
  glg: "glg_Latn",
  isl: "isl_Latn",
  gle: "gle_Latn",
  cym: "cym_Latn",
  afr: "afr_Latn",
  amh: "amh_Ethi",
  azj: "azj_Latn",
  aze: "azj_Latn",
  bel: "bel_Cyrl",
  bos: "bos_Latn",
  kat: "kat_Geor",
  kaz: "kaz_Cyrl",
  khm: "khm_Khmr",
  lao: "lao_Laoo",
  khk: "khk_Cyrl",
  mon: "khk_Cyrl",
  mya: "mya_Mymr",
  bur: "mya_Mymr",
  npi: "npi_Deva",
  nep: "npi_Deva",
  sin: "sin_Sinh",
  uzn: "uzn_Latn",
  uzb: "uzn_Latn",
  hye: "hye_Armn",
  arm: "hye_Armn",
  mlt: "mlt_Latn",
  ltz: "ltz_Latn",
  pan: "pan_Guru",
  hau: "hau_Latn",
  yor: "yor_Latn",
  ibo: "ibo_Latn",
  zul: "zul_Latn",
  epo: "epo_Latn",
};

/** NLLB code → closest MoCoMo locale for UI labels. */
const NLLB_TO_LOCALE: Partial<Record<NllbCode, Locale>> = Object.fromEntries(
  Object.entries(LOCALE_TO_NLLB).map(([locale, nllb]) => [nllb, locale as Locale])
);

export function localeToNllb(locale: Locale): NllbCode {
  return LOCALE_TO_NLLB[locale];
}

export function nllbToLocale(code: NllbCode): Locale | null {
  return NLLB_TO_LOCALE[code] ?? null;
}

export function iso6393ToNllb(iso6393: string): NllbCode | null {
  return ISO6393_TO_NLLB[iso6393] ?? null;
}
