/** Paths (dirs or files) archived to archive/games/ by the game-removal change. */
export const WEB_MOVE_SET = [
  // routes
  "src/app/games",
  "src/app/play",
  "src/app/sketch-quiz",
  "src/app/liar-game",
  "src/app/apt",
  "src/app/diorama",
  "src/app/omok",
  "src/app/rps",
  "src/app/word-chain",
  "src/app/api/minigames",
  "src/app/api/apt",
  "src/app/api/mobile/games",
  // components
  "src/components/games",
  "src/components/minigames",
  "src/components/sketch-quiz",
  "src/components/spot-diff",
  "src/components/chess",
  "src/components/baduk",
  "src/components/janggi",
  "src/components/omok",
  "src/components/reversi",
  "src/components/tower-rush",
  "src/components/piano-rush",
  "src/components/parking-rush",
  "src/components/liar-game",
  "src/components/apt",
  "src/components/activities",
  "src/components/chat/chat-game-share-card.tsx",
  "src/components/layout/games-nav-section.tsx",
  "src/components/profile/profile-minigame-async.tsx",
  "src/components/profile/profile-minigame-panel.tsx",
  "src/components/compose/apt-mailbox-link.tsx",
  "src/components/live/overlays/live-games-hub-link.tsx",
  "src/components/live/overlays/live-overlay-games-bridge.tsx",
  "src/components/live/overlays/live-overlay-chosung-quiz.tsx",
  "src/components/live/overlays/live-overlay-quiz.tsx",
  "src/components/live/overlays/live-overlay-wheel.tsx",
  "src/components/live/overlays/live-overlay-word-guess.tsx",
  // hooks
  "src/hooks/use-minigame-match.ts",
  "src/hooks/use-minigame-room.ts",
  "src/hooks/use-sketch-quiz-match.ts",
  "src/hooks/use-sketch-quiz-room.ts",
  "src/hooks/use-apt-first-entry.ts",
  "src/hooks/use-apt-home-socket.ts",
  "src/hooks/use-apt-world-socket.ts",
  // lib
  "src/lib/minigames",
  "src/lib/apt",
  "src/lib/diorama",
  "src/lib/activities",
  "src/lib/apt-public-gate.ts",
  "src/lib/apt-route.ts",
  "src/lib/games-catalog.ts",
  "src/lib/games-lobby.ts",
  "src/lib/chat-game-share.ts",
  "src/lib/sketch-quiz-types.ts",
  "src/lib/sketch-quiz-words.ts",
  "src/lib/live-overlays/chosung.ts",
  "src/lib/live-overlays/quiz-parse.ts",
  "src/lib/live-overlays/wheel-theme.ts",
  // actions
  "src/actions/apt.ts",
  "src/actions/apt-bondee.ts",
  "src/actions/apt-cohabitation.ts",
  "src/actions/apt-daily.ts",
  "src/actions/apt-diorama.ts",
  "src/actions/apt-economy.ts",
  "src/actions/apt-game.ts",
  "src/actions/apt-iap.ts",
  "src/actions/apt-market.ts",
  "src/actions/apt-presence.ts",
  "src/actions/apt-world.ts",
  "src/actions/admin-apt-economy.ts",
  // APT economy (gold, gold shop, flea, fraud, IAP) + its admin
  "src/actions/admin-cs.ts",
  "src/actions/admin-economy-backup.ts",
  "src/actions/admin-economy-canary.ts",
  "src/actions/admin-economy-config.ts",
  "src/actions/admin-economy-flags.ts",
  "src/actions/admin-economy-health.ts",
  "src/actions/admin-economy-notifications.ts",
  "src/actions/admin-flea.ts",
  "src/actions/admin-fraud-rules.ts",
  "src/actions/admin-fraud.ts",
  "src/actions/admin-gold-shop.ts",
  "src/actions/admin-market.ts",
  "src/app/admin/economy",
  "src/app/api/iap",
  "src/app/api/economy",
  "src/app/api/cron/iap-retry",
  "src/app/api/cron/iap-voided",
  "src/components/admin/admin-cs-panel.tsx",
  "src/components/admin/admin-economy-backup-panel.tsx",
  "src/components/admin/admin-economy-canary-panel.tsx",
  "src/components/admin/admin-economy-config-panel.tsx",
  "src/components/admin/admin-economy-dashboard.tsx",
  "src/components/admin/admin-economy-flags-panel.tsx",
  "src/components/admin/admin-economy-health-panel.tsx",
  "src/components/admin/admin-economy-notifications-panel.tsx",
  "src/components/admin/admin-economy-nav.tsx",
  "src/components/admin/admin-flea-panel.tsx",
  "src/components/admin/admin-fraud-panel.tsx",
  "src/components/admin/admin-fraud-rules-panel.tsx",
  "src/components/admin/admin-gold-shop-panel.tsx",
  "src/components/admin/admin-market-panel.tsx",
  "src/components/admin/gold-shop-offer-preview.tsx",
  "src/components/providers/local-home-session-sync.tsx",
  "src/components/community-server/channels/activities-channel.tsx",
  // socket server
  "server/minigames",
  "server/word-chain",
  "server/apt-home-store.ts",
  "server/apt-world-store.ts",
  "server/liar-game-store.ts",
  "server/sketch-quiz-store.ts",
  // standalone game + assets + tooling
  "games",
  "public/apt",
  "public/diorama",
  "public/chess",
  "public/piano-rush",
  "public/spot-diff",
  "scripts/build-word-chain-dictionary.ts",
  "scripts/capture-apt-mobile.mjs",
  "scripts/capture-apt-room-preview.mjs",
  "scripts/capture-corner-sample.mjs",
  "scripts/capture-diorama.mjs",
  "scripts/capture-rc1-living.mjs",
  "scripts/debug-apt-blank.mjs",
  "scripts/diag-apt-diorama-smoke.mjs",
  "scripts/diag-apt-iso-scene.mjs",
];

export function inMoveSet(file, set = WEB_MOVE_SET) {
  const f = file.replace(/\\/g, "/");
  return set.some((p) => f === p || f.startsWith(p + "/"));
}
