/** 경매 보증금 — 1 MOCO = $5 USD 가치 */
export const AUCTION_MOCO_USD_VALUE = 5;

/** 입찰 시 동결하는 고정 보증금 (2 MOCO = $10) */
export const AUCTION_BID_DEPOSIT_MOCO = 2;

export const AUCTION_BID_DEPOSIT_USD = AUCTION_BID_DEPOSIT_MOCO * AUCTION_MOCO_USD_VALUE;

export const AUCTION_DEPOSIT_USD_CENTS_PER_MOCO = AUCTION_MOCO_USD_VALUE * 100;

export const AUCTION_DEPOSIT_SOURCE_FORFEIT = "AUCTION_DEPOSIT_FORFEIT";

export const INSUFFICIENT_DEPOSIT_ERROR = "보증금 MOCO가 부족합니다.";
