/** Events & subculture map copy — use with `useI18n().u`. */
export function eventsUi(u: (ko: string, en: string) => string) {
  return {
    back: u("뒤로", "Back"),
    eventsTitle: u("이벤트", "Events"),
    mapTitle: u("서브컬처 맵", "Subculture map"),
    categoryLine: u("팬아트 · 코스프레 · 굿즈 · 오프라인 · 버츄얼", "Fan art · cosplay · goods · offline · virtual"),
    tabAll: u("전체", "All"),
    tabFanart: u("팬아트", "Fan art"),
    tabCosplay: u("코스프레", "Cosplay"),
    tabGoods: u("굿즈", "Goods"),
    tabVirtual: u("버츄얼", "Virtual"),
    tabMeetup: u("행사", "Meetups"),
    tabOther: u("이벤트", "Events"),
    ended: u("종료", "Ended"),
    participants: (n: number) => u(`${n}명 참여`, `${n} joined`),
    registerEvent: u("이벤트 등록", "Create event"),
    emptyEventsTitle: u("✨ 아직 진행 중인 이벤트가 없습니다. ✨", "✨ No active events yet. ✨"),
    emptyEventsSub: u("첫 번째 이벤트를 등록해보세요.", "Be the first to create one."),
    loadListError: u("이벤트 목록을 불러오지 못했습니다.", "Could not load events."),
    loadEventError: u("이벤트를 불러오지 못했습니다.", "Could not load event."),
    prize: (p: string) => u(`상품: ${p}`, `Prize: ${p}`),
    join: u("참여하기", "Join"),
    joining: u("참여 중", "Joined"),
    joinDone: u("참여 완료", "Joined"),
    joinFail: u("참여에 실패했습니다.", "Could not join."),
    sponsorBtn: u("스폰서 광고 구매 (MOCO)", "Buy sponsor ad (MOCO)"),
    sponsorDone: u("스폰서 광고가 등록되었습니다.", "Sponsor ad registered."),
    mapTabVenue: u("행사장", "Venues"),
    mapTabMaid: u("메이드 카페", "Maid cafés"),
    mapTabRec: u("추천", "Picks"),
    statusOngoing: u("진행 중", "Ongoing"),
    statusUpcoming: u("예정", "Upcoming"),
    statusPermanent: u("상설", "Permanent"),
    googleMaps: u("Google 지도", "Google Maps"),
    pinUserRec: u("유저 추천", "User pick"),
    pinMaidOpen: u("상설 영업", "Always open"),
    pinRecShort: u("추천", "Pick"),
    pinMaidShort: u("상설", "Permanent"),
    mapAttributionA11y: u("지도 타일 저작권 정보", "Map tile attribution"),
    closePopupA11y: u("팝업 닫기", "Close popup"),
    roadView: u("로드뷰", "Street View"),
    badgeOfficial: u("공식 자동", "Official"),
    badgeMaid: u("메이드 카페", "Maid café"),
    badgeUserRec: u("유저 추천", "User pick"),
    googleSearch: u("Google 검색", "Google search"),
    official: u("공식", "Official"),
    saveFail: u("저장에 실패했습니다.", "Could not save."),
    panelToggle: (open: boolean) =>
      open ? u("목록 접기", "Collapse list") : u("목록으로 반 나누기", "Split with list"),
    loadMapError: u("지도를 불러오지 못했습니다.", "Could not load map."),
    noPinsTitle: u("표시할 행사가 없습니다", "Nothing to show"),
    noPinsSub: u("등록된 서브컬처 행사 핀이 없습니다.", "No subculture event pins registered."),
    pickOnMap: u("지도에서 원하는 위치를 탭하세요", "Tap the map to pick a location"),
    recHint: u("유저 추천 · 초록 핀", "User picks · green pins"),
    loginToRec: u("로그인 후 추천 장소를 등록할 수 있습니다.", "Sign in to add a recommended place."),
    add: u("추가", "Add"),
    cancel: u("취소", "Cancel"),
    selectedCoords: (lat: number, lng: number) =>
      u(`선택 좌표 · ${lat.toFixed(5)}, ${lng.toFixed(5)}`, `Selected · ${lat.toFixed(5)}, ${lng.toFixed(5)}`),
    placeNamePh: u("장소 이름", "Place name"),
    memoPh: u("한 줄 메모 (선택)", "Short note (optional)"),
    placeNameRequired: u("장소 이름을 입력해 주세요.", "Enter a place name."),
    saving: u("저장 중…", "Saving…"),
    register: u("등록", "Add"),
    emptyRec: u("아직 추천 장소가 없습니다.", "No recommended places yet."),
    emptyTab: u("이 탭에 표시할 항목이 없습니다", "Nothing in this tab"),
    sponsorTitle: u("이벤트 스폰서 광고", "Event sponsor ad"),
    sponsorSub: u("웹과 동일 — MOCO로 기간 광고를 구매합니다.", "Same as web — buy timed ads with MOCO."),
    days: (d: number) => u(`${d}일`, `${d} days`),
    quote: (moco: string) => u(`견적: ${moco}`, `Quote: ${moco}`),
    balance: (n: number) => u(`구매 MOCO 잔액: ${n.toLocaleString()}`, `MOCO balance: ${n.toLocaleString()}`),
    insufficientMoco: u(
      "잔액이 부족합니다. mocomo.net 웹에서 MOCO를 충전해 주세요.",
      "Insufficient balance. Top up MOCO on mocomo.net."
    ),
    quoteLoadFail: u("광고 견적을 불러오지 못했습니다.", "Could not load ad quote."),
    purchaseFail: u("광고 구매에 실패했습니다.", "Could not purchase ad."),
    close: u("닫기", "Close"),
    purchaseBusy: u("처리 중…", "Processing…"),
    purchase: u("광고 구매", "Buy ad"),
  };
}

export type EventsUi = ReturnType<typeof eventsUi>;
