
import type { TFn } from "@/i18n/types";

/** Events and subculture map copy. */
export function eventsUi(t: TFn) {
  return {
    back: t("m.common.back"),
    eventsTitle: t("m.common.events"),
    mapTitle: t("m.events.subculture_map"),
    categoryLine: t("m.events.fan_art_cosplay_goods_offline_virtual"),
    tabAll: t("m.common.all"),
    tabFanart: t("m.events.fan_art"),
    tabCosplay: t("m.events.cosplay"),
    tabGoods: t("m.events.goods"),
    tabVirtual: t("m.events.virtual"),
    tabMeetup: t("m.events.meetups"),
    tabOther: t("m.common.events"),
    ended: t("m.common.ended"),
    participants: (n: number) => t("m.events.n_joined", { n: String(n) }),
    registerEvent: t("m.events.create_event"),
    emptyEventsTitle: t("m.events.no_active_events_yet"),
    emptyEventsSub: t("m.events.be_the_first_to_create_one"),
    loadListError: t("m.events.could_not_load_events"),
    loadEventError: t("m.events.could_not_load_event"),
    prize: (p: string) => t("m.events.prize_p", { p: String(p) }),
    join: t("m.common.join"),
    joining: t("m.common.joined"),
    joinDone: t("m.common.joined"),
    joinFail: t("m.common.could_not_join"),
    sponsorBtn: t("m.events.buy_sponsor_ad_moco"),
    sponsorDone: t("m.events.sponsor_ad_registered"),
    mapTabVenue: t("m.events.venues"),
    mapTabMaid: t("m.events.maid_caf_s"),
    mapTabRec: t("m.events.picks"),
    statusOngoing: t("m.common.ongoing"),
    statusUpcoming: t("m.common.upcoming"),
    statusPermanent: t("m.common.permanent"),
    googleMaps: t("m.common.google_maps"),
    pinUserRec: t("m.events.user_pick"),
    pinMaidOpen: t("m.events.always_open"),
    pinRecShort: t("m.events.pick"),
    pinMaidShort: t("m.common.permanent"),
    mapAttributionA11y: t("m.common.map_tile_attribution"),
    closePopupA11y: t("m.events.close_popup"),
    roadView: t("m.events.street_view"),
    badgeOfficial: t("m.events.official"),
    badgeMaid: t("m.events.maid_caf"),
    badgeUserRec: t("m.events.user_pick"),
    googleSearch: t("m.common.google_search"),
    official: t("m.events.official"),
    saveFail: t("m.common.could_not_save"),
    panelToggle: (open: boolean) =>
      open ? t("m.events.collapse_list") : t("m.events.split_with_list"),
    loadMapError: t("m.events.could_not_load_map"),
    noPinsTitle: t("m.events.nothing_to_show"),
    noPinsSub: t("m.events.no_subculture_event_pins_registered"),
    pickOnMap: t("m.events.tap_the_map_to_pick_a"),
    recHint: t("m.events.user_picks_green_pins"),
    loginToRec: t("m.events.sign_in_to_add_a_recommended"),
    add: t("m.common.add"),
    cancel: t("m.common.cancel"),
    selectedCoords: (lat: number, lng: number) =>
      t("m.events.selected_lat_lng", { lat: String(lat.toFixed(5)), lng: String(lng.toFixed(5)) }),
    placeNamePh: t("m.events.place_name"),
    memoPh: t("m.events.short_note_optional"),
    placeNameRequired: t("m.events.enter_a_place_name"),
    saving: t("m.common.saving"),
    register: t("m.common.add"),
    emptyRec: t("m.events.no_recommended_places_yet"),
    emptyTab: t("m.events.nothing_in_this_tab"),
    sponsorTitle: t("m.events.event_sponsor_ad"),
    sponsorSub: t("m.events.same_as_web_buy_timed_ads"),
    days: (d: number) => t("m.events.d_days", { d: String(d) }),
    quote: (moco: string) => t("m.events.quote_moco", { moco: String(moco) }),
    balance: (n: number) => t("m.events.moco_balance_n", { n: String(n.toLocaleString()) }),
    insufficientMoco: t("m.events.insufficient_balance_top_up_moco_on"),
    quoteLoadFail: t("m.events.could_not_load_ad_quote"),
    purchaseFail: t("m.events.could_not_purchase_ad"),
    close: t("m.common.close"),
    purchaseBusy: t("m.common.processing"),
    purchase: t("m.events.buy_ad"),
  };
}

export type EventsUi = ReturnType<typeof eventsUi>;
