/** Stripe Connect Express self-serve payout countries. Keep in sync with src/lib/marketplace/stripe-supported-countries.ts */
export const DEFAULT_EXPRESS_PAYOUT_COUNTRY = "US";

export const STRIPE_EXPRESS_SUPPORTED_COUNTRIES: { code: string; name: string }[] = [{ code: "US", name: "United States (US)" },
  { code: "JP", name: "Japan (JP)" },
  { code: "CA", name: "Canada (CA)" },
  { code: "GB", name: "United Kingdom (GB)" },
  { code: "AU", name: "Australia (AU)" },
  { code: "NZ", name: "New Zealand (NZ)" },
  { code: "SG", name: "Singapore (SG)" },
  { code: "HK", name: "Hong Kong (HK)" },
  { code: "MY", name: "Malaysia (MY)" },
  { code: "MX", name: "Mexico (MX)" },
  { code: "BR", name: "Brazil (BR)" },
  { code: "DE", name: "Germany (DE)" },
  { code: "FR", name: "France (FR)" },
  { code: "IT", name: "Italy (IT)" },
  { code: "ES", name: "Spain (ES)" },
  { code: "NL", name: "Netherlands (NL)" },
  { code: "BE", name: "Belgium (BE)" },
  { code: "AT", name: "Austria (AT)" },
  { code: "CH", name: "Switzerland (CH)" },
  { code: "SE", name: "Sweden (SE)" },
  { code: "NO", name: "Norway (NO)" },
  { code: "FI", name: "Finland (FI)" },
  { code: "IE", name: "Ireland (IE)" },
  { code: "DK", name: "Denmark (DK)" },
  { code: "PT", name: "Portugal (PT)" },
  { code: "PL", name: "Poland (PL)" },
  { code: "CZ", name: "Czech Republic (CZ)" },
  { code: "HU", name: "Hungary (HU)" },
  { code: "RO", name: "Romania (RO)" },
  { code: "GR", name: "Greece (GR)" },
  { code: "HR", name: "Croatia (HR)" },
  { code: "SK", name: "Slovakia (SK)" },
  { code: "SI", name: "Slovenia (SI)" },
  { code: "BG", name: "Bulgaria (BG)" },
  { code: "LT", name: "Lithuania (LT)" },
  { code: "LV", name: "Latvia (LV)" },
  { code: "EE", name: "Estonia (EE)" },
  { code: "LU", name: "Luxembourg (LU)" },
  { code: "CY", name: "Cyprus (CY)" },
  { code: "MT", name: "Malta (MT)" },
];
