/** Stripe Connect Express self-serve payout countries. Keep in sync with src/lib/marketplace/stripe-supported-countries.ts */
export const DEFAULT_EXPRESS_PAYOUT_COUNTRY = "US";

export const STRIPE_EXPRESS_SUPPORTED_COUNTRIES: { code: string; name: string }[] = [
  { code: "US", name: "미국 (US)" },
  { code: "JP", name: "일본 (JP)" },
  { code: "CA", name: "캐나다 (CA)" },
  { code: "GB", name: "영국 (GB)" },
  { code: "AU", name: "호주 (AU)" },
  { code: "NZ", name: "뉴질랜드 (NZ)" },
  { code: "SG", name: "싱가포르 (SG)" },
  { code: "HK", name: "홍콩 (HK)" },
  { code: "MY", name: "말레이시아 (MY)" },
  { code: "MX", name: "멕시코 (MX)" },
  { code: "BR", name: "브라질 (BR)" },
  { code: "DE", name: "독일 (DE)" },
  { code: "FR", name: "프랑스 (FR)" },
  { code: "IT", name: "이탈리아 (IT)" },
  { code: "ES", name: "스페인 (ES)" },
  { code: "NL", name: "네덜란드 (NL)" },
  { code: "BE", name: "벨기에 (BE)" },
  { code: "AT", name: "오스트리아 (AT)" },
  { code: "CH", name: "스위스 (CH)" },
  { code: "SE", name: "스웨덴 (SE)" },
  { code: "NO", name: "노르웨이 (NO)" },
  { code: "FI", name: "핀란드 (FI)" },
  { code: "IE", name: "아일랜드 (IE)" },
  { code: "DK", name: "덴마크 (DK)" },
  { code: "PT", name: "포르투갈 (PT)" },
  { code: "PL", name: "폴란드 (PL)" },
  { code: "CZ", name: "체코 (CZ)" },
  { code: "HU", name: "헝가리 (HU)" },
  { code: "RO", name: "루마니아 (RO)" },
  { code: "GR", name: "그리스 (GR)" },
  { code: "HR", name: "크로아티아 (HR)" },
  { code: "SK", name: "슬로바키아 (SK)" },
  { code: "SI", name: "슬로베니아 (SI)" },
  { code: "BG", name: "불가리아 (BG)" },
  { code: "LT", name: "리투아니아 (LT)" },
  { code: "LV", name: "라트비아 (LV)" },
  { code: "EE", name: "에스토니아 (EE)" },
  { code: "LU", name: "룩셈부르크 (LU)" },
  { code: "CY", name: "키프러스 (CY)" },
  { code: "MT", name: "몰타 (MT)" },
];
