-- Video donations: 1 integer = 0.01 MOCO. Playback settlement and refunds.
ALTER TYPE "MocoDonationStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gemBalanceHundredths" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GemPurchase" ADD COLUMN IF NOT EXISTS "remainingHundredths" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GiftEvent" ADD COLUMN IF NOT EXISTS "gemsHundredths" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GiftEventAllocation" ADD COLUMN IF NOT EXISTS "gemsUsedHundredths" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "VoiceChannel" ADD COLUMN IF NOT EXISTS "videoDonationEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "VoiceChannel" ADD COLUMN IF NOT EXISTS "videoDonationRateCentiPer10Sec" INTEGER NOT NULL DEFAULT 10;

ALTER TABLE "MocoDonation" ADD COLUMN IF NOT EXISTS "mocoAmountHundredths" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MocoDonation" ADD COLUMN IF NOT EXISTS "mocoCenti" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MocoDonation" ADD COLUMN IF NOT EXISTS "settledAt" TIMESTAMP(3);
ALTER TABLE "MocoDonation" ADD COLUMN IF NOT EXISTS "refundedAt" TIMESTAMP(3);
ALTER TABLE "MocoDonation" ADD COLUMN IF NOT EXISTS "refundReason" VARCHAR(40);

ALTER TABLE "PlatformWallet" ADD COLUMN IF NOT EXISTS "settlementMocoPointsHundredths" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlatformWalletLedger" ADD COLUMN IF NOT EXISTS "deltaHundredths" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlatformWalletLedger" ADD COLUMN IF NOT EXISTS "balanceAfterHundredths" INTEGER NOT NULL DEFAULT 0;
