/**
 * Versioned mobile API paths (Phase 1 server).
 * Keep in sync with docs/MOBILE_API_CONTRACT.md
 */
export const MobileApi = {
  auth: {
    login: "/api/mobile/auth/login",
    refresh: "/api/mobile/auth/refresh",
    logout: "/api/mobile/auth/logout",
    oauthPkce: "/api/mobile/auth/oauth/pkce",
  },
  feed: "/api/mobile/feed",
  reels: "/api/mobile/reels",
  search: "/api/mobile/search",
  post: (id: string) => `/api/mobile/posts/${id}`,
  postShareCard: (id: string) => `/api/mobile/posts/${id}/share-card`,
  postLike: (id: string) => `/api/mobile/posts/${id}/like`,
  postStar: (id: string) => `/api/mobile/posts/${id}/star`,
  postRepost: (id: string) => `/api/mobile/posts/${id}/repost`,
  postProfileFeature: (id: string) => `/api/mobile/posts/${id}/profile-feature`,
  postComments: (id: string) => `/api/mobile/posts/${id}/comments`,
  userMute: "/api/mobile/users/mute",
  userBlockReport: "/api/mobile/users/block-report",
  commentLike: (id: string) => `/api/mobile/comments/${id}/like`,
  follow: "/api/mobile/follow",
  me: "/api/mobile/me",
  user: (username: string) => `/api/mobile/users/${encodeURIComponent(username)}`,
  postsCreate: "/api/mobile/posts",
  notifications: "/api/mobile/notifications",
  pushRegister: "/api/mobile/push/register",
  upload: "/api/mobile/upload",
  messages: "/api/mobile/messages",
  calls: "/api/mobile/calls",
  callAccept: (id: string) => `/api/mobile/calls/${id}/accept`,
  callEnd: (id: string) => `/api/mobile/calls/${id}/end`,
  live: "/api/mobile/live",
  marketplace: "/api/mobile/marketplace",
  marketplacePhone: "/api/mobile/marketplace/phone",
  accountBank: "/api/mobile/account/bank",
  starMarket: "/api/mobile/market",
  starMarketEmoticons: "/api/mobile/market/emoticons",
  starMarketMine: "/api/mobile/market/mine",
  marketSellAccess: "/api/mobile/market/sell-access",
  marketOrders: "/api/mobile/market/orders",
  marketListings: "/api/mobile/market/listings",
  marketSellerOnboarding: "/api/mobile/market/seller/onboarding",
  webSession: "/api/mobile/auth/web-session",
  community: "/api/mobile/community",
  events: "/api/mobile/events",
  star: "/api/mobile/star",
  anime: "/api/mobile/anime",
  animeSlug: (slug: string) => `/api/mobile/anime/${encodeURIComponent(slug)}`,
  wallet: "/api/mobile/wallet",
  walletEarnings: "/api/mobile/wallet/earnings",
  checkout: "/api/mobile/checkout",
  checkoutConfirm: "/api/mobile/checkout/confirm",
  callBookings: "/api/mobile/call-bookings",
  callBooking: (id: string) => `/api/mobile/call-bookings/${id}`,
  callBookingCreator: (userId: string) => `/api/mobile/call-bookings/creator/${userId}`,
  callBookingAccept: (id: string) => `/api/mobile/call-bookings/${id}/accept`,
  callBookingReject: (id: string) => `/api/mobile/call-bookings/${id}/reject`,
  callBookingJoin: (id: string) => `/api/mobile/call-bookings/${id}/join`,
  callBookingComplete: (id: string) => `/api/mobile/call-bookings/${id}/complete`,
  callBookingRefund: (id: string) => `/api/mobile/call-bookings/${id}/refund`,
  creatorCallSettings: "/api/mobile/me/creator-call-settings",
  starMarketCheckout: (id: string) => `/api/mobile/market/${id}/checkout`,
  liveAlerts: (id: string) => `/api/mobile/live/${id}/alerts`,
  games: "/api/mobile/games",
  highlights: "/api/mobile/highlights",
} as const;
