import { StyleSheet } from "react-native";
import { radii, shadows, spacing, type ThemeColors } from "@/theme/tokens";

/** Shared MoCoMo folk chrome for compose image/video editors. */
export function createComposeEditorStyles(colors: ThemeColors, isDark: boolean) {
  const previewCanvas = isDark ? "#0A0E18" : "#152238";
  const sheetBorder = isDark ? colors.hairline : "rgba(27, 74, 140, 0.12)";

  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },

    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: spacing.sm,
      paddingBottom: spacing.xs,
      gap: spacing.sm,
    },
    headerSide: { width: 44, height: 40, justifyContent: "center" },
    headerTitle: {
      flex: 1,
      textAlign: "center",
      fontSize: 17,
      fontWeight: "800",
      color: colors.brand,
      letterSpacing: -0.2,
    },

    previewFrame: {
      flex: 1,
      marginHorizontal: spacing.md,
      marginBottom: spacing.xs,
      borderRadius: radii.lg,
      borderWidth: 2,
      borderColor: isDark ? "rgba(107, 163, 232, 0.22)" : "rgba(27, 74, 140, 0.18)",
      backgroundColor: previewCanvas,
      overflow: "hidden",
      ...shadows.folkSm,
    },
    previewWrap: {
      flex: 1,
      minHeight: 240,
      backgroundColor: previewCanvas,
    },
    busyOverlay: {
      ...StyleSheet.absoluteFill,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(0,0,0,0.35)",
    },
    pauseBadge: {
      ...StyleSheet.absoluteFill,
      alignItems: "center",
      justifyContent: "center",
    },
    error: {
      color: colors.danger,
      textAlign: "center",
      fontSize: 12,
      fontWeight: "600",
      paddingHorizontal: spacing.md,
      paddingTop: 6,
    },

    toolStrip: {
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      gap: spacing.sm,
      alignItems: "center",
    },
    toolPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: radii.pill,
      borderWidth: 1.5,
      borderColor: isDark ? "rgba(107, 163, 232, 0.28)" : "rgba(27, 74, 140, 0.2)",
      backgroundColor: colors.surfaceRaised,
      ...shadows.folkSm,
    },
    toolPillActive: {
      backgroundColor: colors.terracotta,
      borderColor: colors.terracotta,
    },
    toolPillLabel: {
      color: colors.brand,
      fontSize: 13,
      fontWeight: "800",
    },
    toolPillLabelActive: { color: colors.textOnAccent },

    sheet: {
      marginHorizontal: spacing.md,
      marginTop: spacing.xs,
      borderRadius: radii.lg,
      borderWidth: 1.5,
      borderColor: sheetBorder,
      backgroundColor: colors.surfaceRaised,
      paddingTop: spacing.sm,
      ...shadows.folk,
    },
    sheetBody: { paddingHorizontal: spacing.md, gap: 10, paddingBottom: 8 },
    sheetHint: {
      color: colors.textMuted,
      textAlign: "center",
      fontWeight: "600",
      fontSize: 13,
    },
    trackRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: colors.muted,
      borderRadius: radii.md,
      padding: 12,
      borderWidth: 1,
      borderColor: sheetBorder,
    },
    trackLabel: { flex: 1, color: colors.text, fontWeight: "700", fontSize: 14 },
    sheetMutedBtn: { alignSelf: "center", paddingVertical: 6 },
    sheetMutedBtnText: { color: colors.textMuted, fontWeight: "700" },

    filterRow: { paddingHorizontal: 12, gap: 10, paddingBottom: 8 },
    filterChip: { alignItems: "center", width: 72 },
    filterPreview: {
      width: 64,
      height: 64,
      borderRadius: radii.sm,
      borderWidth: 2,
      borderColor: "transparent",
    },
    filterPreviewActive: { borderColor: colors.terracotta },
    filterLabel: {
      marginTop: 6,
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: "700",
    },
    filterLabelActive: { color: colors.terracotta },

    adjustRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    adjustLabel: { color: colors.text, fontWeight: "700", fontSize: 14 },
    adjustBtns: { flexDirection: "row", alignItems: "center", gap: 12 },
    adjustBtn: {
      width: 32,
      height: 32,
      borderRadius: radii.sm,
      backgroundColor: colors.muted,
      borderWidth: 1,
      borderColor: sheetBorder,
      alignItems: "center",
      justifyContent: "center",
    },
    adjustBtnText: { color: colors.brand, fontWeight: "800", fontSize: 18 },
    adjustValue: { color: colors.text, fontWeight: "700", minWidth: 36, textAlign: "center" },
    adjustActions: { flexDirection: "row", justifyContent: "space-around", marginTop: 8 },
    miniAction: {
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 6,
      borderRadius: radii.sm,
      backgroundColor: colors.muted,
      borderWidth: 1,
      borderColor: sheetBorder,
      minWidth: 52,
    },
    miniActionLabel: { color: colors.textSecondary, fontSize: 10, fontWeight: "700" },

    aspectRow: { paddingHorizontal: 12, gap: 8, paddingBottom: 8 },
    aspectChip: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: radii.pill,
      backgroundColor: colors.muted,
      borderWidth: 1.5,
      borderColor: sheetBorder,
    },
    aspectChipMuted: { opacity: 0.45 },
    aspectText: { color: colors.brand, fontWeight: "800", fontSize: 13 },

    sheetActions: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: spacing.md,
      paddingTop: 8,
      paddingBottom: spacing.sm,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: sheetBorder,
    },
    sheetCancel: { color: colors.textMuted, fontWeight: "700", fontSize: 15 },
    sheetTitle: { color: colors.text, fontWeight: "800", fontSize: 15 },
    sheetDone: { color: colors.terracotta, fontWeight: "800", fontSize: 15 },

    bottomBar: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: spacing.md,
      paddingTop: spacing.sm,
      gap: spacing.sm,
      borderTopWidth: 2,
      borderTopColor: isDark ? colors.hairline : "rgba(27, 74, 140, 0.1)",
      backgroundColor: colors.surface,
    },
    thumbRow: { alignItems: "center", gap: 8, paddingRight: 8 },
    thumb: {
      width: 48,
      height: 48,
      borderRadius: radii.sm,
      overflow: "hidden",
      borderWidth: 2,
      borderColor: "transparent",
    },
    thumbActive: { borderColor: colors.terracotta },
    thumbImg: { width: "100%", height: "100%" },
    addThumb: {
      width: 48,
      height: 48,
      borderRadius: radii.sm,
      backgroundColor: colors.muted,
      borderWidth: 1.5,
      borderColor: sheetBorder,
      borderStyle: "dashed",
      alignItems: "center",
      justifyContent: "center",
    },
    nextBtn: {
      backgroundColor: colors.terracotta,
      paddingHorizontal: 20,
      paddingVertical: 11,
      borderRadius: radii.pill,
      minWidth: 76,
      alignItems: "center",
      borderWidth: 2,
      borderColor: isDark ? "rgba(107, 163, 232, 0.18)" : "rgba(27, 74, 140, 0.15)",
      ...shadows.folkSm,
    },
    nextBtnDisabled: { opacity: 0.5 },
    nextBtnText: { color: colors.textOnAccent, fontWeight: "800", fontSize: 15 },

    textModalRoot: {
      flex: 1,
      backgroundColor: "rgba(20, 40, 72, 0.45)",
      justifyContent: "center",
      padding: spacing.lg,
    },
    textModalCard: {
      backgroundColor: colors.surfaceRaised,
      borderRadius: radii.lg,
      padding: spacing.md,
      gap: 12,
      borderWidth: 2,
      borderColor: sheetBorder,
      ...shadows.folk,
    },
    textModalTitle: { color: colors.text, fontWeight: "800", fontSize: 16 },
    textModalInput: {
      borderRadius: radii.md,
      backgroundColor: colors.muted,
      borderWidth: 1,
      borderColor: sheetBorder,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: colors.text,
      fontSize: 15,
    },
    textModalActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },

    /** Video editor extras */
    topDoneBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.terracotta,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: isDark ? "rgba(107, 163, 232, 0.18)" : "rgba(27, 74, 140, 0.12)",
    },
    playbackRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: spacing.md,
      paddingVertical: 10,
      gap: 12,
    },
    timeText: {
      flex: 1,
      color: colors.text,
      fontWeight: "700",
      fontSize: 13,
      textAlign: "center",
    },
    playbackActions: { flexDirection: "row", gap: 14 },
    timelineBlock: { paddingHorizontal: spacing.md, gap: 8, paddingBottom: 6 },
    trackThumbStrip: { flex: 1, flexDirection: "row", alignItems: "center", gap: 8 },
    trackHint: { color: colors.textSecondary, fontSize: 12, fontWeight: "600" },
    trimActions: { flexDirection: "row", gap: 6 },
    miniBtn: {
      width: 28,
      height: 28,
      borderRadius: radii.sm,
      backgroundColor: colors.muted,
      borderWidth: 1,
      borderColor: sheetBorder,
      alignItems: "center",
      justifyContent: "center",
    },
    miniBtnText: { color: colors.brand, fontWeight: "800", fontSize: 14 },
    timelineHint: {
      color: colors.textMuted,
      fontSize: 11,
      textAlign: "center",
      fontWeight: "600",
    },
    videoToolbar: {
      flexDirection: "row",
      justifyContent: "space-around",
      paddingTop: spacing.sm,
      paddingHorizontal: spacing.sm,
      marginHorizontal: spacing.md,
      marginBottom: spacing.xs,
      borderRadius: radii.lg,
      borderWidth: 1.5,
      borderColor: sheetBorder,
      backgroundColor: colors.surfaceRaised,
      ...shadows.folkSm,
    },
    videoToolItem: { alignItems: "center", gap: 4, minWidth: 64, paddingVertical: 8 },
    videoToolLabel: { color: colors.textSecondary, fontSize: 11, fontWeight: "700" },
    sheetMuted: {
      color: colors.textMuted,
      textAlign: "center",
      padding: spacing.md,
      fontWeight: "600",
    },
  });
}

export type ComposeEditorStyles = ReturnType<typeof createComposeEditorStyles>;
