
import type { TFn } from "@/i18n/types";

/** Live feature copy. */
export function liveUi(t: TFn) {
  return {
    feature: t("m.common.live"),
    back: t("m.common.back"),
    close: t("m.common.close"),
    all: t("m.common.all"),
    retry: t("m.common.try_again"),
    loadHubError: t("m.live.could_not_load_live_streams"),
    noSearchResults: t("m.live.no_search_results"),
    connectError: t("m.live.could_not_connect_to_the_live"),
    streamEnded: t("m.live.this_stream_has_ended"),
    browseOther: t("m.live.browse_other_live_streams"),
    liveHome: t("m.live.live_home"),
    watch: t("m.live.watch"),
    expandVideo: t("m.live.expand_video"),
    exitLandscape: t("m.live.exit_landscape"),
    showChat: t("m.live.show_chat"),
    hideChat: t("m.live.hide_chat"),
    showFeatures: t("m.live.show_features"),
    hideFeatures: t("m.live.hide_features"),
    adult19: t("m.live.19_adult_stream"),
    adultSub: t("m.live.verified_adults_only"),
    adultVerify: t("m.live.age_verification"),
    adultVerifyWatch: t("m.live.verify_age_to_watch"),
    chatUnavailable: t("m.live.you_cannot_join_this_chat"),
    tapRetry: t("m.live.tap_to_retry"),
    noLiveNow: t("m.live.no_live_streams_right_now"),
    noLiveSub: t("m.live.new_streams_will_appear_here_when"),
    openLiveA11y: (title: string) => t("m.live.open_live_title", { title: String(title) }),
    noStreamsEmpty: t("m.live.no_streams_are_live"),
    searchPlaceholder: t("m.live.nickname_title"),
    clearSearch: t("m.live.clear_search"),
    searchToggle: (open: boolean) => (open ? t("m.live.close_search") : t("m.common.search")),
    scheduled: t("m.live.scheduled"),
    channelView: t("m.live.view_channel"),
    shareLink: t("m.live.share_link"),
    donation: t("m.live.support"),
    mocoDonation: t("m.live.moco_tip"),
    scrollToPlay: t("m.live.scroll_to_play"),
    watchOnSource: t("m.live.watch_on_the_source_site"),
    openExternal: t("m.live.watch_in_browser"),
    chatTitle: t("m.common.chat"),
    viewersWatching: (n: number) =>
      t("m.live.n_watching", { n: String(n.toLocaleString()) }),
    chatEmpty: t("m.live.no_messages_yet_say_hello"),
    chatSendFailed: t("m.live.could_not_send_message"),
    chatPlaceholderImmersive: t("m.live.type_a_message"),
    chatPlaceholder: t("m.live.chat_message"),
    send: t("m.common.send"),
    videoDonation: t("m.live.video_tip"),
    sfxDonation: t("m.live.sound_effect"),
    cheerCp: t("m.live.cheer_cp"),
    mission: t("m.live.mission"),
    roulette: t("m.live.roulette"),
    mocoCheer: t("m.live.moco_cheer"),
    goLiveTitle: t("m.live.go_live"),
    goLiveLead: t("m.live.video_plays_in_youtube_twitch_or"),
    goLiveStartFailed: t("m.live.could_not_start_the_stream"),
    accountsLoadFailed: t("m.live.could_not_load_accounts"),
    streamingAccountRequired: t("m.live.verified_streaming_account_required"),
    streamingAccountHint: t("m.live.connect_and_verify_youtube_twitch_or"),
    connectAccountsWeb: t("m.live.connect_accounts_on_web"),
    viewLiveNow: t("m.live.view_live_streams"),
    streamTitleLabel: t("m.live.stream_title"),
    streamTitlePlaceholder: t("m.live.today_s_stream"),
    streamTitleChannelLive: (name: string) => t("m.live.name_live", { name: String(name) }),
    streamingAccountLabel: t("m.live.streaming_account"),
    categoryLabel: t("m.common.category"),
    startStream: t("m.live.go_live"),
    viewerCountSuffix: t("m.live.text"),
    kitAudioLive: t("m.live.audio_live"),
    kitReceivingHost: t("m.live.receiving_host_audio"),
    kitWaitingConnection: t("m.live.waiting_to_connect"),
    kitWaitingVideo: t("m.live.waiting_for_video"),
    kitConnecting: t("m.live.connecting_to_live"),
    alertRoulette: t("m.live.roulette"),
    alertProfile: t("m.live.profile"),
  };
}

export type LiveUi = ReturnType<typeof liveUi>;
