/** Live feature copy — use with `useI18n().u`. */
export function liveUi(u: (ko: string, en: string) => string) {
  return {
    feature: u("라이브", "Live"),
    back: u("뒤로", "Back"),
    close: u("닫기", "Close"),
    all: u("전체", "All"),
    retry: u("다시 시도", "Try again"),
    loadHubError: u("라이브를 불러오지 못했습니다.", "Could not load live streams."),
    noSearchResults: u("검색 결과가 없습니다.", "No search results."),
    connectError: u("라이브에 연결하지 못했습니다.", "Could not connect to the live stream."),
    streamEnded: u("방송이 종료되었습니다", "This stream has ended"),
    browseOther: u("다른 라이브 방송을 둘러보세요.", "Browse other live streams."),
    liveHome: u("라이브 홈", "Live home"),
    watch: u("시청하기", "Watch"),
    adult19: u("19+ 성인 방송", "19+ adult stream"),
    adultSub: u("본인인증된 회원만 시청할 수 있습니다.", "Verified adults only."),
    adultVerify: u("성인 본인인증", "Age verification"),
    adultVerifyWatch: u("성인 본인인증 후 시청", "Verify age to watch"),
    chatUnavailable: u("채팅에 참여할 수 없습니다.", "You cannot join this chat."),
    tapRetry: u("탭하여 다시 시도", "Tap to retry"),
    noLiveNow: u("현재 라이브 방송이 없습니다", "No live streams right now"),
    noLiveSub: u("새로운 방송이 시작되면 이곳에 표시됩니다", "New streams will appear here when they start"),
    openLiveA11y: (title: string) => u(`${title} 라이브 열기`, `Open live: ${title}`),
    noStreamsEmpty: u("방송중인 방송이 없습니다", "No streams are live"),
    searchPlaceholder: u("닉네임, 제목", "Nickname, title"),
    clearSearch: u("검색어 지우기", "Clear search"),
    searchToggle: (open: boolean) => (open ? u("검색 닫기", "Close search") : u("검색", "Search")),
    scheduled: u("예약됨", "Scheduled"),
    channelView: u("채널 보기", "View channel"),
    shareLink: u("링크 공유", "Share link"),
    donation: u("후원", "Support"),
    mocoDonation: u("MOCO 후원", "MOCO tip"),
    scrollToPlay: u("스크롤하면 재생됩니다", "Scroll to play"),
    watchOnSource: u("원본 페이지에서 시청해 주세요.", "Watch on the source site."),
    openExternal: u("새 창에서 시청하기", "Watch in browser"),
    chatTitle: u("채팅", "Chat"),
    viewersWatching: (n: number) =>
      u(`${n.toLocaleString()}명 시청`, `${n.toLocaleString()} watching`),
    chatEmpty: u("아직 채팅이 없습니다. 첫 메시지를 남겨 보세요.", "No messages yet. Say hello!"),
    chatSendFailed: u("채팅 전송에 실패했습니다.", "Could not send message."),
    chatPlaceholderImmersive: u("채팅을 입력해 주세요.", "Type a message…"),
    chatPlaceholder: u("채팅 메시지...", "Chat message…"),
    send: u("전송", "Send"),
    videoDonation: u("영상 후원", "Video tip"),
    sfxDonation: u("효과음", "Sound effect"),
    cheerCp: u("응원 CP", "Cheer CP"),
    mission: u("미션", "Mission"),
    roulette: u("룰렛", "Roulette"),
    mocoCheer: u("MOCO 응원", "MOCO cheer"),
    goLiveTitle: u("라이브 방송 시작", "Go live"),
    goLiveLead: u(
      "영상은 YouTube · Twitch · 치지직 플레이어로만 표시됩니다. 채팅은 MoCoMo에서 제공합니다.",
      "Video plays in YouTube, Twitch, or CHZZK players only. Chat is on MoCoMo."
    ),
    goLiveStartFailed: u("방송을 시작하지 못했습니다.", "Could not start the stream."),
    accountsLoadFailed: u("계정 목록을 불러오지 못했습니다.", "Could not load accounts."),
    streamingAccountRequired: u("인증된 스트리밍 계정이 필요합니다", "Verified streaming account required"),
    streamingAccountHint: u(
      "웹 설정에서 YouTube · Twitch · 치지직 계정을 연결·인증한 뒤 앱에서 방송을 시작할 수 있습니다.",
      "Connect and verify YouTube, Twitch, or CHZZK in web settings, then go live from the app."
    ),
    connectAccountsWeb: u("웹에서 계정 연결", "Connect accounts on web"),
    viewLiveNow: u("진행 중 방송 보기", "View live streams"),
    streamTitleLabel: u("방송 제목", "Stream title"),
    streamTitlePlaceholder: u("오늘의 라이브", "Today's stream"),
    streamTitleChannelLive: (name: string) => u(`${name} 라이브`, `${name} live`),
    streamingAccountLabel: u("스트리밍 계정", "Streaming account"),
    categoryLabel: u("카테고리", "Category"),
    startStream: u("방송 시작", "Go live"),
    viewerCountSuffix: u("명", ""),
    kitAudioLive: u("음성 라이브", "Audio live"),
    kitReceivingHost: u("호스트 오디오 수신 중", "Receiving host audio"),
    kitWaitingConnection: u("연결 대기 중…", "Waiting to connect…"),
    kitWaitingVideo: u("영상 트랙을 기다리는 중…", "Waiting for video…"),
    kitConnecting: u("라이브 연결 중…", "Connecting to live…"),
    alertRoulette: u("룰렛", "Roulette"),
    alertProfile: u("프로필", "Profile"),
  };
}

export type LiveUi = ReturnType<typeof liveUi>;
